import CoreGraphics

// Generated by Scripts/generate-swift-component-initializers.mjs.
extension MeshGradient {
  public init(
    colors: [ShaderColor] = MeshGradient.presets[0].params.colors,
    distortion: Float = MeshGradient.presets[0].params.distortion,
    swirl: Float = MeshGradient.presets[0].params.swirl,
    grainMixer: Float = MeshGradient.presets[0].params.grainMixer,
    grainOverlay: Float = MeshGradient.presets[0].params.grainOverlay,
    fit: ShaderFit = MeshGradient.presets[0].sizing.fit,
    scale: Float = MeshGradient.presets[0].sizing.scale,
    rotation: Float = MeshGradient.presets[0].sizing.rotation,
    originX: Float = MeshGradient.presets[0].sizing.originX,
    originY: Float = MeshGradient.presets[0].sizing.originY,
    offsetX: Float = MeshGradient.presets[0].sizing.offsetX,
    offsetY: Float = MeshGradient.presets[0].sizing.offsetY,
    worldWidth: Float = MeshGradient.presets[0].sizing.worldWidth,
    worldHeight: Float = MeshGradient.presets[0].sizing.worldHeight,
    speed: Float = MeshGradient.presets[0].motion.speed,
    frame: Float = MeshGradient.presets[0].motion.frame,
    minPixelRatio: Float = MeshGradient.presets[0].renderOptions.minPixelRatio,
    maxPixelCount: Int = MeshGradient.presets[0].renderOptions.maxPixelCount,
    width: CGFloat? = MeshGradient.presets[0].renderOptions.width,
    height: CGFloat? = MeshGradient.presets[0].renderOptions.height,
    image: ShaderImage? = MeshGradient.presets[0].image
  ) {
    self.init(
      params: MeshGradientParams(
        colors: colors,
        distortion: distortion,
        swirl: swirl,
        grainMixer: grainMixer,
        grainOverlay: grainOverlay
      ),
      sizing: ShaderSizingParams(
        fit: fit, scale: scale, rotation: rotation, originX: originX, originY: originY,
        offsetX: offsetX, offsetY: offsetY, worldWidth: worldWidth, worldHeight: worldHeight),
      motion: ShaderMotionParams(speed: speed, frame: frame),
      renderOptions: ShaderRenderOptions(
        minPixelRatio: minPixelRatio, maxPixelCount: maxPixelCount, width: width, height: height),
      image: image
    )
  }
}

extension SmokeRing {
  public init(
    colorBack: ShaderColor = SmokeRing.presets[0].params.colorBack,
    colors: [ShaderColor] = SmokeRing.presets[0].params.colors,
    noiseScale: Float = SmokeRing.presets[0].params.noiseScale,
    thickness: Float = SmokeRing.presets[0].params.thickness,
    radius: Float = SmokeRing.presets[0].params.radius,
    innerShape: Float = SmokeRing.presets[0].params.innerShape,
    noiseIterations: Float = SmokeRing.presets[0].params.noiseIterations,
    fit: ShaderFit = SmokeRing.presets[0].sizing.fit,
    scale: Float = SmokeRing.presets[0].sizing.scale,
    rotation: Float = SmokeRing.presets[0].sizing.rotation,
    originX: Float = SmokeRing.presets[0].sizing.originX,
    originY: Float = SmokeRing.presets[0].sizing.originY,
    offsetX: Float = SmokeRing.presets[0].sizing.offsetX,
    offsetY: Float = SmokeRing.presets[0].sizing.offsetY,
    worldWidth: Float = SmokeRing.presets[0].sizing.worldWidth,
    worldHeight: Float = SmokeRing.presets[0].sizing.worldHeight,
    speed: Float = SmokeRing.presets[0].motion.speed,
    frame: Float = SmokeRing.presets[0].motion.frame,
    minPixelRatio: Float = SmokeRing.presets[0].renderOptions.minPixelRatio,
    maxPixelCount: Int = SmokeRing.presets[0].renderOptions.maxPixelCount,
    width: CGFloat? = SmokeRing.presets[0].renderOptions.width,
    height: CGFloat? = SmokeRing.presets[0].renderOptions.height,
    image: ShaderImage? = SmokeRing.presets[0].image
  ) {
    self.init(
      params: SmokeRingParams(
        colorBack: colorBack,
        colors: colors,
        noiseScale: noiseScale,
        thickness: thickness,
        radius: radius,
        innerShape: innerShape,
        noiseIterations: noiseIterations
      ),
      sizing: ShaderSizingParams(
        fit: fit, scale: scale, rotation: rotation, originX: originX, originY: originY,
        offsetX: offsetX, offsetY: offsetY, worldWidth: worldWidth, worldHeight: worldHeight),
      motion: ShaderMotionParams(speed: speed, frame: frame),
      renderOptions: ShaderRenderOptions(
        minPixelRatio: minPixelRatio, maxPixelCount: maxPixelCount, width: width, height: height),
      image: image
    )
  }
}

extension NeuroNoise {
  public init(
    colorFront: ShaderColor = NeuroNoise.presets[0].params.colorFront,
    colorMid: ShaderColor = NeuroNoise.presets[0].params.colorMid,
    colorBack: ShaderColor = NeuroNoise.presets[0].params.colorBack,
    brightness: Float = NeuroNoise.presets[0].params.brightness,
    contrast: Float = NeuroNoise.presets[0].params.contrast,
    fit: ShaderFit = NeuroNoise.presets[0].sizing.fit,
    scale: Float = NeuroNoise.presets[0].sizing.scale,
    rotation: Float = NeuroNoise.presets[0].sizing.rotation,
    originX: Float = NeuroNoise.presets[0].sizing.originX,
    originY: Float = NeuroNoise.presets[0].sizing.originY,
    offsetX: Float = NeuroNoise.presets[0].sizing.offsetX,
    offsetY: Float = NeuroNoise.presets[0].sizing.offsetY,
    worldWidth: Float = NeuroNoise.presets[0].sizing.worldWidth,
    worldHeight: Float = NeuroNoise.presets[0].sizing.worldHeight,
    speed: Float = NeuroNoise.presets[0].motion.speed,
    frame: Float = NeuroNoise.presets[0].motion.frame,
    minPixelRatio: Float = NeuroNoise.presets[0].renderOptions.minPixelRatio,
    maxPixelCount: Int = NeuroNoise.presets[0].renderOptions.maxPixelCount,
    width: CGFloat? = NeuroNoise.presets[0].renderOptions.width,
    height: CGFloat? = NeuroNoise.presets[0].renderOptions.height,
    image: ShaderImage? = NeuroNoise.presets[0].image
  ) {
    self.init(
      params: NeuroNoiseParams(
        colorFront: colorFront,
        colorMid: colorMid,
        colorBack: colorBack,
        brightness: brightness,
        contrast: contrast
      ),
      sizing: ShaderSizingParams(
        fit: fit, scale: scale, rotation: rotation, originX: originX, originY: originY,
        offsetX: offsetX, offsetY: offsetY, worldWidth: worldWidth, worldHeight: worldHeight),
      motion: ShaderMotionParams(speed: speed, frame: frame),
      renderOptions: ShaderRenderOptions(
        minPixelRatio: minPixelRatio, maxPixelCount: maxPixelCount, width: width, height: height),
      image: image
    )
  }
}

extension DotOrbit {
  public init(
    colorBack: ShaderColor = DotOrbit.presets[0].params.colorBack,
    colors: [ShaderColor] = DotOrbit.presets[0].params.colors,
    stepsPerColor: Float = DotOrbit.presets[0].params.stepsPerColor,
    size: Float = DotOrbit.presets[0].params.size,
    sizeRange: Float = DotOrbit.presets[0].params.sizeRange,
    spreading: Float = DotOrbit.presets[0].params.spreading,
    fit: ShaderFit = DotOrbit.presets[0].sizing.fit,
    scale: Float = DotOrbit.presets[0].sizing.scale,
    rotation: Float = DotOrbit.presets[0].sizing.rotation,
    originX: Float = DotOrbit.presets[0].sizing.originX,
    originY: Float = DotOrbit.presets[0].sizing.originY,
    offsetX: Float = DotOrbit.presets[0].sizing.offsetX,
    offsetY: Float = DotOrbit.presets[0].sizing.offsetY,
    worldWidth: Float = DotOrbit.presets[0].sizing.worldWidth,
    worldHeight: Float = DotOrbit.presets[0].sizing.worldHeight,
    speed: Float = DotOrbit.presets[0].motion.speed,
    frame: Float = DotOrbit.presets[0].motion.frame,
    minPixelRatio: Float = DotOrbit.presets[0].renderOptions.minPixelRatio,
    maxPixelCount: Int = DotOrbit.presets[0].renderOptions.maxPixelCount,
    width: CGFloat? = DotOrbit.presets[0].renderOptions.width,
    height: CGFloat? = DotOrbit.presets[0].renderOptions.height,
    image: ShaderImage? = DotOrbit.presets[0].image
  ) {
    self.init(
      params: DotOrbitParams(
        colorBack: colorBack,
        colors: colors,
        stepsPerColor: stepsPerColor,
        size: size,
        sizeRange: sizeRange,
        spreading: spreading
      ),
      sizing: ShaderSizingParams(
        fit: fit, scale: scale, rotation: rotation, originX: originX, originY: originY,
        offsetX: offsetX, offsetY: offsetY, worldWidth: worldWidth, worldHeight: worldHeight),
      motion: ShaderMotionParams(speed: speed, frame: frame),
      renderOptions: ShaderRenderOptions(
        minPixelRatio: minPixelRatio, maxPixelCount: maxPixelCount, width: width, height: height),
      image: image
    )
  }
}

extension DotGrid {
  public init(
    colorBack: ShaderColor = DotGrid.presets[0].params.colorBack,
    colorFill: ShaderColor = DotGrid.presets[0].params.colorFill,
    colorStroke: ShaderColor = DotGrid.presets[0].params.colorStroke,
    dotSize: Float = DotGrid.presets[0].params.dotSize,
    gapX: Float = DotGrid.presets[0].params.gapX,
    gapY: Float = DotGrid.presets[0].params.gapY,
    strokeWidth: Float = DotGrid.presets[0].params.strokeWidth,
    sizeRange: Float = DotGrid.presets[0].params.sizeRange,
    opacityRange: Float = DotGrid.presets[0].params.opacityRange,
    shape: DotGridShape = DotGrid.presets[0].params.shape,
    fit: ShaderFit = DotGrid.presets[0].sizing.fit,
    scale: Float = DotGrid.presets[0].sizing.scale,
    rotation: Float = DotGrid.presets[0].sizing.rotation,
    originX: Float = DotGrid.presets[0].sizing.originX,
    originY: Float = DotGrid.presets[0].sizing.originY,
    offsetX: Float = DotGrid.presets[0].sizing.offsetX,
    offsetY: Float = DotGrid.presets[0].sizing.offsetY,
    worldWidth: Float = DotGrid.presets[0].sizing.worldWidth,
    worldHeight: Float = DotGrid.presets[0].sizing.worldHeight,
    speed: Float = DotGrid.presets[0].motion.speed,
    frame: Float = DotGrid.presets[0].motion.frame,
    minPixelRatio: Float = DotGrid.presets[0].renderOptions.minPixelRatio,
    maxPixelCount: Int = DotGrid.presets[0].renderOptions.maxPixelCount,
    width: CGFloat? = DotGrid.presets[0].renderOptions.width,
    height: CGFloat? = DotGrid.presets[0].renderOptions.height,
    image: ShaderImage? = DotGrid.presets[0].image
  ) {
    self.init(
      params: DotGridParams(
        colorBack: colorBack,
        colorFill: colorFill,
        colorStroke: colorStroke,
        dotSize: dotSize,
        gapX: gapX,
        gapY: gapY,
        strokeWidth: strokeWidth,
        sizeRange: sizeRange,
        opacityRange: opacityRange,
        shape: shape
      ),
      sizing: ShaderSizingParams(
        fit: fit, scale: scale, rotation: rotation, originX: originX, originY: originY,
        offsetX: offsetX, offsetY: offsetY, worldWidth: worldWidth, worldHeight: worldHeight),
      motion: ShaderMotionParams(speed: speed, frame: frame),
      renderOptions: ShaderRenderOptions(
        minPixelRatio: minPixelRatio, maxPixelCount: maxPixelCount, width: width, height: height),
      image: image
    )
  }
}

extension SimplexNoise {
  public init(
    colors: [ShaderColor] = SimplexNoise.presets[0].params.colors,
    stepsPerColor: Float = SimplexNoise.presets[0].params.stepsPerColor,
    softness: Float = SimplexNoise.presets[0].params.softness,
    fit: ShaderFit = SimplexNoise.presets[0].sizing.fit,
    scale: Float = SimplexNoise.presets[0].sizing.scale,
    rotation: Float = SimplexNoise.presets[0].sizing.rotation,
    originX: Float = SimplexNoise.presets[0].sizing.originX,
    originY: Float = SimplexNoise.presets[0].sizing.originY,
    offsetX: Float = SimplexNoise.presets[0].sizing.offsetX,
    offsetY: Float = SimplexNoise.presets[0].sizing.offsetY,
    worldWidth: Float = SimplexNoise.presets[0].sizing.worldWidth,
    worldHeight: Float = SimplexNoise.presets[0].sizing.worldHeight,
    speed: Float = SimplexNoise.presets[0].motion.speed,
    frame: Float = SimplexNoise.presets[0].motion.frame,
    minPixelRatio: Float = SimplexNoise.presets[0].renderOptions.minPixelRatio,
    maxPixelCount: Int = SimplexNoise.presets[0].renderOptions.maxPixelCount,
    width: CGFloat? = SimplexNoise.presets[0].renderOptions.width,
    height: CGFloat? = SimplexNoise.presets[0].renderOptions.height,
    image: ShaderImage? = SimplexNoise.presets[0].image
  ) {
    self.init(
      params: SimplexNoiseParams(
        colors: colors,
        stepsPerColor: stepsPerColor,
        softness: softness
      ),
      sizing: ShaderSizingParams(
        fit: fit, scale: scale, rotation: rotation, originX: originX, originY: originY,
        offsetX: offsetX, offsetY: offsetY, worldWidth: worldWidth, worldHeight: worldHeight),
      motion: ShaderMotionParams(speed: speed, frame: frame),
      renderOptions: ShaderRenderOptions(
        minPixelRatio: minPixelRatio, maxPixelCount: maxPixelCount, width: width, height: height),
      image: image
    )
  }
}

extension Metaballs {
  public init(
    colorBack: ShaderColor = Metaballs.presets[0].params.colorBack,
    colors: [ShaderColor] = Metaballs.presets[0].params.colors,
    count: Float = Metaballs.presets[0].params.count,
    size: Float = Metaballs.presets[0].params.size,
    sizeRange: Float = Metaballs.presets[0].params.sizeRange,
    fit: ShaderFit = Metaballs.presets[0].sizing.fit,
    scale: Float = Metaballs.presets[0].sizing.scale,
    rotation: Float = Metaballs.presets[0].sizing.rotation,
    originX: Float = Metaballs.presets[0].sizing.originX,
    originY: Float = Metaballs.presets[0].sizing.originY,
    offsetX: Float = Metaballs.presets[0].sizing.offsetX,
    offsetY: Float = Metaballs.presets[0].sizing.offsetY,
    worldWidth: Float = Metaballs.presets[0].sizing.worldWidth,
    worldHeight: Float = Metaballs.presets[0].sizing.worldHeight,
    speed: Float = Metaballs.presets[0].motion.speed,
    frame: Float = Metaballs.presets[0].motion.frame,
    minPixelRatio: Float = Metaballs.presets[0].renderOptions.minPixelRatio,
    maxPixelCount: Int = Metaballs.presets[0].renderOptions.maxPixelCount,
    width: CGFloat? = Metaballs.presets[0].renderOptions.width,
    height: CGFloat? = Metaballs.presets[0].renderOptions.height,
    image: ShaderImage? = Metaballs.presets[0].image
  ) {
    self.init(
      params: MetaballsParams(
        colorBack: colorBack,
        colors: colors,
        count: count,
        size: size,
        sizeRange: sizeRange
      ),
      sizing: ShaderSizingParams(
        fit: fit, scale: scale, rotation: rotation, originX: originX, originY: originY,
        offsetX: offsetX, offsetY: offsetY, worldWidth: worldWidth, worldHeight: worldHeight),
      motion: ShaderMotionParams(speed: speed, frame: frame),
      renderOptions: ShaderRenderOptions(
        minPixelRatio: minPixelRatio, maxPixelCount: maxPixelCount, width: width, height: height),
      image: image
    )
  }
}

extension Waves {
  public init(
    colorFront: ShaderColor = Waves.presets[0].params.colorFront,
    colorBack: ShaderColor = Waves.presets[0].params.colorBack,
    shape: Float = Waves.presets[0].params.shape,
    frequency: Float = Waves.presets[0].params.frequency,
    amplitude: Float = Waves.presets[0].params.amplitude,
    spacing: Float = Waves.presets[0].params.spacing,
    proportion: Float = Waves.presets[0].params.proportion,
    softness: Float = Waves.presets[0].params.softness,
    fit: ShaderFit = Waves.presets[0].sizing.fit,
    scale: Float = Waves.presets[0].sizing.scale,
    rotation: Float = Waves.presets[0].sizing.rotation,
    originX: Float = Waves.presets[0].sizing.originX,
    originY: Float = Waves.presets[0].sizing.originY,
    offsetX: Float = Waves.presets[0].sizing.offsetX,
    offsetY: Float = Waves.presets[0].sizing.offsetY,
    worldWidth: Float = Waves.presets[0].sizing.worldWidth,
    worldHeight: Float = Waves.presets[0].sizing.worldHeight,
    speed: Float = Waves.presets[0].motion.speed,
    frame: Float = Waves.presets[0].motion.frame,
    minPixelRatio: Float = Waves.presets[0].renderOptions.minPixelRatio,
    maxPixelCount: Int = Waves.presets[0].renderOptions.maxPixelCount,
    width: CGFloat? = Waves.presets[0].renderOptions.width,
    height: CGFloat? = Waves.presets[0].renderOptions.height,
    image: ShaderImage? = Waves.presets[0].image
  ) {
    self.init(
      params: WavesParams(
        colorFront: colorFront,
        colorBack: colorBack,
        shape: shape,
        frequency: frequency,
        amplitude: amplitude,
        spacing: spacing,
        proportion: proportion,
        softness: softness
      ),
      sizing: ShaderSizingParams(
        fit: fit, scale: scale, rotation: rotation, originX: originX, originY: originY,
        offsetX: offsetX, offsetY: offsetY, worldWidth: worldWidth, worldHeight: worldHeight),
      motion: ShaderMotionParams(speed: speed, frame: frame),
      renderOptions: ShaderRenderOptions(
        minPixelRatio: minPixelRatio, maxPixelCount: maxPixelCount, width: width, height: height),
      image: image
    )
  }
}

extension PerlinNoise {
  public init(
    colorFront: ShaderColor = PerlinNoise.presets[0].params.colorFront,
    colorBack: ShaderColor = PerlinNoise.presets[0].params.colorBack,
    proportion: Float = PerlinNoise.presets[0].params.proportion,
    softness: Float = PerlinNoise.presets[0].params.softness,
    octaveCount: Float = PerlinNoise.presets[0].params.octaveCount,
    persistence: Float = PerlinNoise.presets[0].params.persistence,
    lacunarity: Float = PerlinNoise.presets[0].params.lacunarity,
    fit: ShaderFit = PerlinNoise.presets[0].sizing.fit,
    scale: Float = PerlinNoise.presets[0].sizing.scale,
    rotation: Float = PerlinNoise.presets[0].sizing.rotation,
    originX: Float = PerlinNoise.presets[0].sizing.originX,
    originY: Float = PerlinNoise.presets[0].sizing.originY,
    offsetX: Float = PerlinNoise.presets[0].sizing.offsetX,
    offsetY: Float = PerlinNoise.presets[0].sizing.offsetY,
    worldWidth: Float = PerlinNoise.presets[0].sizing.worldWidth,
    worldHeight: Float = PerlinNoise.presets[0].sizing.worldHeight,
    speed: Float = PerlinNoise.presets[0].motion.speed,
    frame: Float = PerlinNoise.presets[0].motion.frame,
    minPixelRatio: Float = PerlinNoise.presets[0].renderOptions.minPixelRatio,
    maxPixelCount: Int = PerlinNoise.presets[0].renderOptions.maxPixelCount,
    width: CGFloat? = PerlinNoise.presets[0].renderOptions.width,
    height: CGFloat? = PerlinNoise.presets[0].renderOptions.height,
    image: ShaderImage? = PerlinNoise.presets[0].image
  ) {
    self.init(
      params: PerlinNoiseParams(
        colorFront: colorFront,
        colorBack: colorBack,
        proportion: proportion,
        softness: softness,
        octaveCount: octaveCount,
        persistence: persistence,
        lacunarity: lacunarity
      ),
      sizing: ShaderSizingParams(
        fit: fit, scale: scale, rotation: rotation, originX: originX, originY: originY,
        offsetX: offsetX, offsetY: offsetY, worldWidth: worldWidth, worldHeight: worldHeight),
      motion: ShaderMotionParams(speed: speed, frame: frame),
      renderOptions: ShaderRenderOptions(
        minPixelRatio: minPixelRatio, maxPixelCount: maxPixelCount, width: width, height: height),
      image: image
    )
  }
}

extension Voronoi {
  public init(
    colors: [ShaderColor] = Voronoi.presets[0].params.colors,
    stepsPerColor: Float = Voronoi.presets[0].params.stepsPerColor,
    colorGap: ShaderColor = Voronoi.presets[0].params.colorGap,
    colorGlow: ShaderColor = Voronoi.presets[0].params.colorGlow,
    distortion: Float = Voronoi.presets[0].params.distortion,
    gap: Float = Voronoi.presets[0].params.gap,
    glow: Float = Voronoi.presets[0].params.glow,
    fit: ShaderFit = Voronoi.presets[0].sizing.fit,
    scale: Float = Voronoi.presets[0].sizing.scale,
    rotation: Float = Voronoi.presets[0].sizing.rotation,
    originX: Float = Voronoi.presets[0].sizing.originX,
    originY: Float = Voronoi.presets[0].sizing.originY,
    offsetX: Float = Voronoi.presets[0].sizing.offsetX,
    offsetY: Float = Voronoi.presets[0].sizing.offsetY,
    worldWidth: Float = Voronoi.presets[0].sizing.worldWidth,
    worldHeight: Float = Voronoi.presets[0].sizing.worldHeight,
    speed: Float = Voronoi.presets[0].motion.speed,
    frame: Float = Voronoi.presets[0].motion.frame,
    minPixelRatio: Float = Voronoi.presets[0].renderOptions.minPixelRatio,
    maxPixelCount: Int = Voronoi.presets[0].renderOptions.maxPixelCount,
    width: CGFloat? = Voronoi.presets[0].renderOptions.width,
    height: CGFloat? = Voronoi.presets[0].renderOptions.height,
    image: ShaderImage? = Voronoi.presets[0].image
  ) {
    self.init(
      params: VoronoiParams(
        colors: colors,
        stepsPerColor: stepsPerColor,
        colorGap: colorGap,
        colorGlow: colorGlow,
        distortion: distortion,
        gap: gap,
        glow: glow
      ),
      sizing: ShaderSizingParams(
        fit: fit, scale: scale, rotation: rotation, originX: originX, originY: originY,
        offsetX: offsetX, offsetY: offsetY, worldWidth: worldWidth, worldHeight: worldHeight),
      motion: ShaderMotionParams(speed: speed, frame: frame),
      renderOptions: ShaderRenderOptions(
        minPixelRatio: minPixelRatio, maxPixelCount: maxPixelCount, width: width, height: height),
      image: image
    )
  }
}

extension Warp {
  public init(
    colors: [ShaderColor] = Warp.presets[0].params.colors,
    proportion: Float = Warp.presets[0].params.proportion,
    softness: Float = Warp.presets[0].params.softness,
    shape: WarpPattern = Warp.presets[0].params.shape,
    shapeScale: Float = Warp.presets[0].params.shapeScale,
    distortion: Float = Warp.presets[0].params.distortion,
    swirl: Float = Warp.presets[0].params.swirl,
    swirlIterations: Float = Warp.presets[0].params.swirlIterations,
    fit: ShaderFit = Warp.presets[0].sizing.fit,
    scale: Float = Warp.presets[0].sizing.scale,
    rotation: Float = Warp.presets[0].sizing.rotation,
    originX: Float = Warp.presets[0].sizing.originX,
    originY: Float = Warp.presets[0].sizing.originY,
    offsetX: Float = Warp.presets[0].sizing.offsetX,
    offsetY: Float = Warp.presets[0].sizing.offsetY,
    worldWidth: Float = Warp.presets[0].sizing.worldWidth,
    worldHeight: Float = Warp.presets[0].sizing.worldHeight,
    speed: Float = Warp.presets[0].motion.speed,
    frame: Float = Warp.presets[0].motion.frame,
    minPixelRatio: Float = Warp.presets[0].renderOptions.minPixelRatio,
    maxPixelCount: Int = Warp.presets[0].renderOptions.maxPixelCount,
    width: CGFloat? = Warp.presets[0].renderOptions.width,
    height: CGFloat? = Warp.presets[0].renderOptions.height,
    image: ShaderImage? = Warp.presets[0].image
  ) {
    self.init(
      params: WarpParams(
        colors: colors,
        proportion: proportion,
        softness: softness,
        shape: shape,
        shapeScale: shapeScale,
        distortion: distortion,
        swirl: swirl,
        swirlIterations: swirlIterations
      ),
      sizing: ShaderSizingParams(
        fit: fit, scale: scale, rotation: rotation, originX: originX, originY: originY,
        offsetX: offsetX, offsetY: offsetY, worldWidth: worldWidth, worldHeight: worldHeight),
      motion: ShaderMotionParams(speed: speed, frame: frame),
      renderOptions: ShaderRenderOptions(
        minPixelRatio: minPixelRatio, maxPixelCount: maxPixelCount, width: width, height: height),
      image: image
    )
  }
}

extension GodRays {
  public init(
    colorBack: ShaderColor = GodRays.presets[0].params.colorBack,
    colorBloom: ShaderColor = GodRays.presets[0].params.colorBloom,
    colors: [ShaderColor] = GodRays.presets[0].params.colors,
    density: Float = GodRays.presets[0].params.density,
    spotty: Float = GodRays.presets[0].params.spotty,
    midSize: Float = GodRays.presets[0].params.midSize,
    midIntensity: Float = GodRays.presets[0].params.midIntensity,
    intensity: Float = GodRays.presets[0].params.intensity,
    bloom: Float = GodRays.presets[0].params.bloom,
    fit: ShaderFit = GodRays.presets[0].sizing.fit,
    scale: Float = GodRays.presets[0].sizing.scale,
    rotation: Float = GodRays.presets[0].sizing.rotation,
    originX: Float = GodRays.presets[0].sizing.originX,
    originY: Float = GodRays.presets[0].sizing.originY,
    offsetX: Float = GodRays.presets[0].sizing.offsetX,
    offsetY: Float = GodRays.presets[0].sizing.offsetY,
    worldWidth: Float = GodRays.presets[0].sizing.worldWidth,
    worldHeight: Float = GodRays.presets[0].sizing.worldHeight,
    speed: Float = GodRays.presets[0].motion.speed,
    frame: Float = GodRays.presets[0].motion.frame,
    minPixelRatio: Float = GodRays.presets[0].renderOptions.minPixelRatio,
    maxPixelCount: Int = GodRays.presets[0].renderOptions.maxPixelCount,
    width: CGFloat? = GodRays.presets[0].renderOptions.width,
    height: CGFloat? = GodRays.presets[0].renderOptions.height,
    image: ShaderImage? = GodRays.presets[0].image
  ) {
    self.init(
      params: GodRaysParams(
        colorBack: colorBack,
        colorBloom: colorBloom,
        colors: colors,
        density: density,
        spotty: spotty,
        midSize: midSize,
        midIntensity: midIntensity,
        intensity: intensity,
        bloom: bloom
      ),
      sizing: ShaderSizingParams(
        fit: fit, scale: scale, rotation: rotation, originX: originX, originY: originY,
        offsetX: offsetX, offsetY: offsetY, worldWidth: worldWidth, worldHeight: worldHeight),
      motion: ShaderMotionParams(speed: speed, frame: frame),
      renderOptions: ShaderRenderOptions(
        minPixelRatio: minPixelRatio, maxPixelCount: maxPixelCount, width: width, height: height),
      image: image
    )
  }
}

extension Spiral {
  public init(
    colorBack: ShaderColor = Spiral.presets[0].params.colorBack,
    colorFront: ShaderColor = Spiral.presets[0].params.colorFront,
    density: Float = Spiral.presets[0].params.density,
    distortion: Float = Spiral.presets[0].params.distortion,
    strokeWidth: Float = Spiral.presets[0].params.strokeWidth,
    strokeTaper: Float = Spiral.presets[0].params.strokeTaper,
    strokeCap: Float = Spiral.presets[0].params.strokeCap,
    noise: Float = Spiral.presets[0].params.noise,
    noiseFrequency: Float = Spiral.presets[0].params.noiseFrequency,
    softness: Float = Spiral.presets[0].params.softness,
    fit: ShaderFit = Spiral.presets[0].sizing.fit,
    scale: Float = Spiral.presets[0].sizing.scale,
    rotation: Float = Spiral.presets[0].sizing.rotation,
    originX: Float = Spiral.presets[0].sizing.originX,
    originY: Float = Spiral.presets[0].sizing.originY,
    offsetX: Float = Spiral.presets[0].sizing.offsetX,
    offsetY: Float = Spiral.presets[0].sizing.offsetY,
    worldWidth: Float = Spiral.presets[0].sizing.worldWidth,
    worldHeight: Float = Spiral.presets[0].sizing.worldHeight,
    speed: Float = Spiral.presets[0].motion.speed,
    frame: Float = Spiral.presets[0].motion.frame,
    minPixelRatio: Float = Spiral.presets[0].renderOptions.minPixelRatio,
    maxPixelCount: Int = Spiral.presets[0].renderOptions.maxPixelCount,
    width: CGFloat? = Spiral.presets[0].renderOptions.width,
    height: CGFloat? = Spiral.presets[0].renderOptions.height,
    image: ShaderImage? = Spiral.presets[0].image
  ) {
    self.init(
      params: SpiralParams(
        colorBack: colorBack,
        colorFront: colorFront,
        density: density,
        distortion: distortion,
        strokeWidth: strokeWidth,
        strokeTaper: strokeTaper,
        strokeCap: strokeCap,
        noise: noise,
        noiseFrequency: noiseFrequency,
        softness: softness
      ),
      sizing: ShaderSizingParams(
        fit: fit, scale: scale, rotation: rotation, originX: originX, originY: originY,
        offsetX: offsetX, offsetY: offsetY, worldWidth: worldWidth, worldHeight: worldHeight),
      motion: ShaderMotionParams(speed: speed, frame: frame),
      renderOptions: ShaderRenderOptions(
        minPixelRatio: minPixelRatio, maxPixelCount: maxPixelCount, width: width, height: height),
      image: image
    )
  }
}

extension Swirl {
  public init(
    colorBack: ShaderColor = Swirl.presets[0].params.colorBack,
    colors: [ShaderColor] = Swirl.presets[0].params.colors,
    bandCount: Float = Swirl.presets[0].params.bandCount,
    twist: Float = Swirl.presets[0].params.twist,
    center: Float = Swirl.presets[0].params.center,
    proportion: Float = Swirl.presets[0].params.proportion,
    softness: Float = Swirl.presets[0].params.softness,
    noise: Float = Swirl.presets[0].params.noise,
    noiseFrequency: Float = Swirl.presets[0].params.noiseFrequency,
    fit: ShaderFit = Swirl.presets[0].sizing.fit,
    scale: Float = Swirl.presets[0].sizing.scale,
    rotation: Float = Swirl.presets[0].sizing.rotation,
    originX: Float = Swirl.presets[0].sizing.originX,
    originY: Float = Swirl.presets[0].sizing.originY,
    offsetX: Float = Swirl.presets[0].sizing.offsetX,
    offsetY: Float = Swirl.presets[0].sizing.offsetY,
    worldWidth: Float = Swirl.presets[0].sizing.worldWidth,
    worldHeight: Float = Swirl.presets[0].sizing.worldHeight,
    speed: Float = Swirl.presets[0].motion.speed,
    frame: Float = Swirl.presets[0].motion.frame,
    minPixelRatio: Float = Swirl.presets[0].renderOptions.minPixelRatio,
    maxPixelCount: Int = Swirl.presets[0].renderOptions.maxPixelCount,
    width: CGFloat? = Swirl.presets[0].renderOptions.width,
    height: CGFloat? = Swirl.presets[0].renderOptions.height,
    image: ShaderImage? = Swirl.presets[0].image
  ) {
    self.init(
      params: SwirlParams(
        colorBack: colorBack,
        colors: colors,
        bandCount: bandCount,
        twist: twist,
        center: center,
        proportion: proportion,
        softness: softness,
        noise: noise,
        noiseFrequency: noiseFrequency
      ),
      sizing: ShaderSizingParams(
        fit: fit, scale: scale, rotation: rotation, originX: originX, originY: originY,
        offsetX: offsetX, offsetY: offsetY, worldWidth: worldWidth, worldHeight: worldHeight),
      motion: ShaderMotionParams(speed: speed, frame: frame),
      renderOptions: ShaderRenderOptions(
        minPixelRatio: minPixelRatio, maxPixelCount: maxPixelCount, width: width, height: height),
      image: image
    )
  }
}

extension Dithering {
  public init(
    colorBack: ShaderColor = Dithering.presets[0].params.colorBack,
    colorFront: ShaderColor = Dithering.presets[0].params.colorFront,
    shape: DitheringShape = Dithering.presets[0].params.shape,
    type: DitheringType = Dithering.presets[0].params.type,
    size: Float = Dithering.presets[0].params.size,
    fit: ShaderFit = Dithering.presets[0].sizing.fit,
    scale: Float = Dithering.presets[0].sizing.scale,
    rotation: Float = Dithering.presets[0].sizing.rotation,
    originX: Float = Dithering.presets[0].sizing.originX,
    originY: Float = Dithering.presets[0].sizing.originY,
    offsetX: Float = Dithering.presets[0].sizing.offsetX,
    offsetY: Float = Dithering.presets[0].sizing.offsetY,
    worldWidth: Float = Dithering.presets[0].sizing.worldWidth,
    worldHeight: Float = Dithering.presets[0].sizing.worldHeight,
    speed: Float = Dithering.presets[0].motion.speed,
    frame: Float = Dithering.presets[0].motion.frame,
    minPixelRatio: Float = Dithering.presets[0].renderOptions.minPixelRatio,
    maxPixelCount: Int = Dithering.presets[0].renderOptions.maxPixelCount,
    width: CGFloat? = Dithering.presets[0].renderOptions.width,
    height: CGFloat? = Dithering.presets[0].renderOptions.height,
    image: ShaderImage? = Dithering.presets[0].image
  ) {
    self.init(
      params: DitheringParams(
        colorBack: colorBack,
        colorFront: colorFront,
        shape: shape,
        type: type,
        size: size
      ),
      sizing: ShaderSizingParams(
        fit: fit, scale: scale, rotation: rotation, originX: originX, originY: originY,
        offsetX: offsetX, offsetY: offsetY, worldWidth: worldWidth, worldHeight: worldHeight),
      motion: ShaderMotionParams(speed: speed, frame: frame),
      renderOptions: ShaderRenderOptions(
        minPixelRatio: minPixelRatio, maxPixelCount: maxPixelCount, width: width, height: height),
      image: image
    )
  }
}

extension GrainGradient {
  public init(
    colorBack: ShaderColor = GrainGradient.presets[0].params.colorBack,
    colors: [ShaderColor] = GrainGradient.presets[0].params.colors,
    softness: Float = GrainGradient.presets[0].params.softness,
    intensity: Float = GrainGradient.presets[0].params.intensity,
    noise: Float = GrainGradient.presets[0].params.noise,
    shape: GrainGradientShape = GrainGradient.presets[0].params.shape,
    fit: ShaderFit = GrainGradient.presets[0].sizing.fit,
    scale: Float = GrainGradient.presets[0].sizing.scale,
    rotation: Float = GrainGradient.presets[0].sizing.rotation,
    originX: Float = GrainGradient.presets[0].sizing.originX,
    originY: Float = GrainGradient.presets[0].sizing.originY,
    offsetX: Float = GrainGradient.presets[0].sizing.offsetX,
    offsetY: Float = GrainGradient.presets[0].sizing.offsetY,
    worldWidth: Float = GrainGradient.presets[0].sizing.worldWidth,
    worldHeight: Float = GrainGradient.presets[0].sizing.worldHeight,
    speed: Float = GrainGradient.presets[0].motion.speed,
    frame: Float = GrainGradient.presets[0].motion.frame,
    minPixelRatio: Float = GrainGradient.presets[0].renderOptions.minPixelRatio,
    maxPixelCount: Int = GrainGradient.presets[0].renderOptions.maxPixelCount,
    width: CGFloat? = GrainGradient.presets[0].renderOptions.width,
    height: CGFloat? = GrainGradient.presets[0].renderOptions.height,
    image: ShaderImage? = GrainGradient.presets[0].image
  ) {
    self.init(
      params: GrainGradientParams(
        colorBack: colorBack,
        colors: colors,
        softness: softness,
        intensity: intensity,
        noise: noise,
        shape: shape
      ),
      sizing: ShaderSizingParams(
        fit: fit, scale: scale, rotation: rotation, originX: originX, originY: originY,
        offsetX: offsetX, offsetY: offsetY, worldWidth: worldWidth, worldHeight: worldHeight),
      motion: ShaderMotionParams(speed: speed, frame: frame),
      renderOptions: ShaderRenderOptions(
        minPixelRatio: minPixelRatio, maxPixelCount: maxPixelCount, width: width, height: height),
      image: image
    )
  }
}

extension PulsingBorder {
  public init(
    colorBack: ShaderColor = PulsingBorder.presets[0].params.colorBack,
    colors: [ShaderColor] = PulsingBorder.presets[0].params.colors,
    roundness: Float = PulsingBorder.presets[0].params.roundness,
    thickness: Float = PulsingBorder.presets[0].params.thickness,
    marginLeft: Float = PulsingBorder.presets[0].params.marginLeft,
    marginRight: Float = PulsingBorder.presets[0].params.marginRight,
    marginTop: Float = PulsingBorder.presets[0].params.marginTop,
    marginBottom: Float = PulsingBorder.presets[0].params.marginBottom,
    aspectRatio: PulsingBorderAspectRatio = PulsingBorder.presets[0].params.aspectRatio,
    softness: Float = PulsingBorder.presets[0].params.softness,
    intensity: Float = PulsingBorder.presets[0].params.intensity,
    bloom: Float = PulsingBorder.presets[0].params.bloom,
    spots: Float = PulsingBorder.presets[0].params.spots,
    spotSize: Float = PulsingBorder.presets[0].params.spotSize,
    pulse: Float = PulsingBorder.presets[0].params.pulse,
    smoke: Float = PulsingBorder.presets[0].params.smoke,
    smokeSize: Float = PulsingBorder.presets[0].params.smokeSize,
    fit: ShaderFit = PulsingBorder.presets[0].sizing.fit,
    scale: Float = PulsingBorder.presets[0].sizing.scale,
    rotation: Float = PulsingBorder.presets[0].sizing.rotation,
    originX: Float = PulsingBorder.presets[0].sizing.originX,
    originY: Float = PulsingBorder.presets[0].sizing.originY,
    offsetX: Float = PulsingBorder.presets[0].sizing.offsetX,
    offsetY: Float = PulsingBorder.presets[0].sizing.offsetY,
    worldWidth: Float = PulsingBorder.presets[0].sizing.worldWidth,
    worldHeight: Float = PulsingBorder.presets[0].sizing.worldHeight,
    speed: Float = PulsingBorder.presets[0].motion.speed,
    frame: Float = PulsingBorder.presets[0].motion.frame,
    minPixelRatio: Float = PulsingBorder.presets[0].renderOptions.minPixelRatio,
    maxPixelCount: Int = PulsingBorder.presets[0].renderOptions.maxPixelCount,
    width: CGFloat? = PulsingBorder.presets[0].renderOptions.width,
    height: CGFloat? = PulsingBorder.presets[0].renderOptions.height,
    image: ShaderImage? = PulsingBorder.presets[0].image
  ) {
    self.init(
      params: PulsingBorderParams(
        colorBack: colorBack,
        colors: colors,
        roundness: roundness,
        thickness: thickness,
        marginLeft: marginLeft,
        marginRight: marginRight,
        marginTop: marginTop,
        marginBottom: marginBottom,
        aspectRatio: aspectRatio,
        softness: softness,
        intensity: intensity,
        bloom: bloom,
        spots: spots,
        spotSize: spotSize,
        pulse: pulse,
        smoke: smoke,
        smokeSize: smokeSize
      ),
      sizing: ShaderSizingParams(
        fit: fit, scale: scale, rotation: rotation, originX: originX, originY: originY,
        offsetX: offsetX, offsetY: offsetY, worldWidth: worldWidth, worldHeight: worldHeight),
      motion: ShaderMotionParams(speed: speed, frame: frame),
      renderOptions: ShaderRenderOptions(
        minPixelRatio: minPixelRatio, maxPixelCount: maxPixelCount, width: width, height: height),
      image: image
    )
  }
}

extension ColorPanels {
  public init(
    colors: [ShaderColor] = ColorPanels.presets[0].params.colors,
    colorBack: ShaderColor = ColorPanels.presets[0].params.colorBack,
    density: Float = ColorPanels.presets[0].params.density,
    angle1: Float = ColorPanels.presets[0].params.angle1,
    angle2: Float = ColorPanels.presets[0].params.angle2,
    length: Float = ColorPanels.presets[0].params.length,
    edges: Float = ColorPanels.presets[0].params.edges,
    blur: Float = ColorPanels.presets[0].params.blur,
    fadeIn: Float = ColorPanels.presets[0].params.fadeIn,
    fadeOut: Float = ColorPanels.presets[0].params.fadeOut,
    gradient: Float = ColorPanels.presets[0].params.gradient,
    fit: ShaderFit = ColorPanels.presets[0].sizing.fit,
    scale: Float = ColorPanels.presets[0].sizing.scale,
    rotation: Float = ColorPanels.presets[0].sizing.rotation,
    originX: Float = ColorPanels.presets[0].sizing.originX,
    originY: Float = ColorPanels.presets[0].sizing.originY,
    offsetX: Float = ColorPanels.presets[0].sizing.offsetX,
    offsetY: Float = ColorPanels.presets[0].sizing.offsetY,
    worldWidth: Float = ColorPanels.presets[0].sizing.worldWidth,
    worldHeight: Float = ColorPanels.presets[0].sizing.worldHeight,
    speed: Float = ColorPanels.presets[0].motion.speed,
    frame: Float = ColorPanels.presets[0].motion.frame,
    minPixelRatio: Float = ColorPanels.presets[0].renderOptions.minPixelRatio,
    maxPixelCount: Int = ColorPanels.presets[0].renderOptions.maxPixelCount,
    width: CGFloat? = ColorPanels.presets[0].renderOptions.width,
    height: CGFloat? = ColorPanels.presets[0].renderOptions.height,
    image: ShaderImage? = ColorPanels.presets[0].image
  ) {
    self.init(
      params: ColorPanelsParams(
        colors: colors,
        colorBack: colorBack,
        density: density,
        angle1: angle1,
        angle2: angle2,
        length: length,
        edges: edges,
        blur: blur,
        fadeIn: fadeIn,
        fadeOut: fadeOut,
        gradient: gradient
      ),
      sizing: ShaderSizingParams(
        fit: fit, scale: scale, rotation: rotation, originX: originX, originY: originY,
        offsetX: offsetX, offsetY: offsetY, worldWidth: worldWidth, worldHeight: worldHeight),
      motion: ShaderMotionParams(speed: speed, frame: frame),
      renderOptions: ShaderRenderOptions(
        minPixelRatio: minPixelRatio, maxPixelCount: maxPixelCount, width: width, height: height),
      image: image
    )
  }
}

extension StaticMeshGradient {
  public init(
    colors: [ShaderColor] = StaticMeshGradient.presets[0].params.colors,
    positions: Float = StaticMeshGradient.presets[0].params.positions,
    waveX: Float = StaticMeshGradient.presets[0].params.waveX,
    waveXShift: Float = StaticMeshGradient.presets[0].params.waveXShift,
    waveY: Float = StaticMeshGradient.presets[0].params.waveY,
    waveYShift: Float = StaticMeshGradient.presets[0].params.waveYShift,
    mixing: Float = StaticMeshGradient.presets[0].params.mixing,
    grainMixer: Float = StaticMeshGradient.presets[0].params.grainMixer,
    grainOverlay: Float = StaticMeshGradient.presets[0].params.grainOverlay,
    fit: ShaderFit = StaticMeshGradient.presets[0].sizing.fit,
    scale: Float = StaticMeshGradient.presets[0].sizing.scale,
    rotation: Float = StaticMeshGradient.presets[0].sizing.rotation,
    originX: Float = StaticMeshGradient.presets[0].sizing.originX,
    originY: Float = StaticMeshGradient.presets[0].sizing.originY,
    offsetX: Float = StaticMeshGradient.presets[0].sizing.offsetX,
    offsetY: Float = StaticMeshGradient.presets[0].sizing.offsetY,
    worldWidth: Float = StaticMeshGradient.presets[0].sizing.worldWidth,
    worldHeight: Float = StaticMeshGradient.presets[0].sizing.worldHeight,
    speed: Float = StaticMeshGradient.presets[0].motion.speed,
    frame: Float = StaticMeshGradient.presets[0].motion.frame,
    minPixelRatio: Float = StaticMeshGradient.presets[0].renderOptions.minPixelRatio,
    maxPixelCount: Int = StaticMeshGradient.presets[0].renderOptions.maxPixelCount,
    width: CGFloat? = StaticMeshGradient.presets[0].renderOptions.width,
    height: CGFloat? = StaticMeshGradient.presets[0].renderOptions.height,
    image: ShaderImage? = StaticMeshGradient.presets[0].image
  ) {
    self.init(
      params: StaticMeshGradientParams(
        colors: colors,
        positions: positions,
        waveX: waveX,
        waveXShift: waveXShift,
        waveY: waveY,
        waveYShift: waveYShift,
        mixing: mixing,
        grainMixer: grainMixer,
        grainOverlay: grainOverlay
      ),
      sizing: ShaderSizingParams(
        fit: fit, scale: scale, rotation: rotation, originX: originX, originY: originY,
        offsetX: offsetX, offsetY: offsetY, worldWidth: worldWidth, worldHeight: worldHeight),
      motion: ShaderMotionParams(speed: speed, frame: frame),
      renderOptions: ShaderRenderOptions(
        minPixelRatio: minPixelRatio, maxPixelCount: maxPixelCount, width: width, height: height),
      image: image
    )
  }
}

extension StaticRadialGradient {
  public init(
    colorBack: ShaderColor = StaticRadialGradient.presets[0].params.colorBack,
    colors: [ShaderColor] = StaticRadialGradient.presets[0].params.colors,
    radius: Float = StaticRadialGradient.presets[0].params.radius,
    focalDistance: Float = StaticRadialGradient.presets[0].params.focalDistance,
    focalAngle: Float = StaticRadialGradient.presets[0].params.focalAngle,
    falloff: Float = StaticRadialGradient.presets[0].params.falloff,
    mixing: Float = StaticRadialGradient.presets[0].params.mixing,
    distortion: Float = StaticRadialGradient.presets[0].params.distortion,
    distortionShift: Float = StaticRadialGradient.presets[0].params.distortionShift,
    distortionFreq: Float = StaticRadialGradient.presets[0].params.distortionFreq,
    grainMixer: Float = StaticRadialGradient.presets[0].params.grainMixer,
    grainOverlay: Float = StaticRadialGradient.presets[0].params.grainOverlay,
    fit: ShaderFit = StaticRadialGradient.presets[0].sizing.fit,
    scale: Float = StaticRadialGradient.presets[0].sizing.scale,
    rotation: Float = StaticRadialGradient.presets[0].sizing.rotation,
    originX: Float = StaticRadialGradient.presets[0].sizing.originX,
    originY: Float = StaticRadialGradient.presets[0].sizing.originY,
    offsetX: Float = StaticRadialGradient.presets[0].sizing.offsetX,
    offsetY: Float = StaticRadialGradient.presets[0].sizing.offsetY,
    worldWidth: Float = StaticRadialGradient.presets[0].sizing.worldWidth,
    worldHeight: Float = StaticRadialGradient.presets[0].sizing.worldHeight,
    speed: Float = StaticRadialGradient.presets[0].motion.speed,
    frame: Float = StaticRadialGradient.presets[0].motion.frame,
    minPixelRatio: Float = StaticRadialGradient.presets[0].renderOptions.minPixelRatio,
    maxPixelCount: Int = StaticRadialGradient.presets[0].renderOptions.maxPixelCount,
    width: CGFloat? = StaticRadialGradient.presets[0].renderOptions.width,
    height: CGFloat? = StaticRadialGradient.presets[0].renderOptions.height,
    image: ShaderImage? = StaticRadialGradient.presets[0].image
  ) {
    self.init(
      params: StaticRadialGradientParams(
        colorBack: colorBack,
        colors: colors,
        radius: radius,
        focalDistance: focalDistance,
        focalAngle: focalAngle,
        falloff: falloff,
        mixing: mixing,
        distortion: distortion,
        distortionShift: distortionShift,
        distortionFreq: distortionFreq,
        grainMixer: grainMixer,
        grainOverlay: grainOverlay
      ),
      sizing: ShaderSizingParams(
        fit: fit, scale: scale, rotation: rotation, originX: originX, originY: originY,
        offsetX: offsetX, offsetY: offsetY, worldWidth: worldWidth, worldHeight: worldHeight),
      motion: ShaderMotionParams(speed: speed, frame: frame),
      renderOptions: ShaderRenderOptions(
        minPixelRatio: minPixelRatio, maxPixelCount: maxPixelCount, width: width, height: height),
      image: image
    )
  }
}

extension PaperTexture {
  public init(
    colorFront: ShaderColor = PaperTexture.presets[0].params.colorFront,
    colorBack: ShaderColor = PaperTexture.presets[0].params.colorBack,
    contrast: Float = PaperTexture.presets[0].params.contrast,
    roughness: Float = PaperTexture.presets[0].params.roughness,
    fiber: Float = PaperTexture.presets[0].params.fiber,
    fiberSize: Float = PaperTexture.presets[0].params.fiberSize,
    crumples: Float = PaperTexture.presets[0].params.crumples,
    foldCount: Float = PaperTexture.presets[0].params.foldCount,
    folds: Float = PaperTexture.presets[0].params.folds,
    fade: Float = PaperTexture.presets[0].params.fade,
    crumpleSize: Float = PaperTexture.presets[0].params.crumpleSize,
    drops: Float = PaperTexture.presets[0].params.drops,
    seed: Float = PaperTexture.presets[0].params.seed,
    fit: ShaderFit = PaperTexture.presets[0].sizing.fit,
    scale: Float = PaperTexture.presets[0].sizing.scale,
    rotation: Float = PaperTexture.presets[0].sizing.rotation,
    originX: Float = PaperTexture.presets[0].sizing.originX,
    originY: Float = PaperTexture.presets[0].sizing.originY,
    offsetX: Float = PaperTexture.presets[0].sizing.offsetX,
    offsetY: Float = PaperTexture.presets[0].sizing.offsetY,
    worldWidth: Float = PaperTexture.presets[0].sizing.worldWidth,
    worldHeight: Float = PaperTexture.presets[0].sizing.worldHeight,
    speed: Float = PaperTexture.presets[0].motion.speed,
    frame: Float = PaperTexture.presets[0].motion.frame,
    minPixelRatio: Float = PaperTexture.presets[0].renderOptions.minPixelRatio,
    maxPixelCount: Int = PaperTexture.presets[0].renderOptions.maxPixelCount,
    width: CGFloat? = PaperTexture.presets[0].renderOptions.width,
    height: CGFloat? = PaperTexture.presets[0].renderOptions.height,
    image: ShaderImage? = PaperTexture.presets[0].image
  ) {
    self.init(
      params: PaperTextureParams(
        colorFront: colorFront,
        colorBack: colorBack,
        contrast: contrast,
        roughness: roughness,
        fiber: fiber,
        fiberSize: fiberSize,
        crumples: crumples,
        foldCount: foldCount,
        folds: folds,
        fade: fade,
        crumpleSize: crumpleSize,
        drops: drops,
        seed: seed
      ),
      sizing: ShaderSizingParams(
        fit: fit, scale: scale, rotation: rotation, originX: originX, originY: originY,
        offsetX: offsetX, offsetY: offsetY, worldWidth: worldWidth, worldHeight: worldHeight),
      motion: ShaderMotionParams(speed: speed, frame: frame),
      renderOptions: ShaderRenderOptions(
        minPixelRatio: minPixelRatio, maxPixelCount: maxPixelCount, width: width, height: height),
      image: image
    )
  }
}

extension FlutedGlass {
  public init(
    colorBack: ShaderColor = FlutedGlass.presets[0].params.colorBack,
    colorShadow: ShaderColor = FlutedGlass.presets[0].params.colorShadow,
    colorHighlight: ShaderColor = FlutedGlass.presets[0].params.colorHighlight,
    shadows: Float = FlutedGlass.presets[0].params.shadows,
    size: Float = FlutedGlass.presets[0].params.size,
    angle: Float = FlutedGlass.presets[0].params.angle,
    distortion: Float = FlutedGlass.presets[0].params.distortion,
    shift: Float = FlutedGlass.presets[0].params.shift,
    blur: Float = FlutedGlass.presets[0].params.blur,
    edges: Float = FlutedGlass.presets[0].params.edges,
    marginLeft: Float = FlutedGlass.presets[0].params.marginLeft,
    marginRight: Float = FlutedGlass.presets[0].params.marginRight,
    marginTop: Float = FlutedGlass.presets[0].params.marginTop,
    marginBottom: Float = FlutedGlass.presets[0].params.marginBottom,
    stretch: Float = FlutedGlass.presets[0].params.stretch,
    distortionShape: GlassDistortionShape = FlutedGlass.presets[0].params.distortionShape,
    highlights: Float = FlutedGlass.presets[0].params.highlights,
    shape: GlassGridShape = FlutedGlass.presets[0].params.shape,
    grainMixer: Float = FlutedGlass.presets[0].params.grainMixer,
    grainOverlay: Float = FlutedGlass.presets[0].params.grainOverlay,
    fit: ShaderFit = FlutedGlass.presets[0].sizing.fit,
    scale: Float = FlutedGlass.presets[0].sizing.scale,
    rotation: Float = FlutedGlass.presets[0].sizing.rotation,
    originX: Float = FlutedGlass.presets[0].sizing.originX,
    originY: Float = FlutedGlass.presets[0].sizing.originY,
    offsetX: Float = FlutedGlass.presets[0].sizing.offsetX,
    offsetY: Float = FlutedGlass.presets[0].sizing.offsetY,
    worldWidth: Float = FlutedGlass.presets[0].sizing.worldWidth,
    worldHeight: Float = FlutedGlass.presets[0].sizing.worldHeight,
    speed: Float = FlutedGlass.presets[0].motion.speed,
    frame: Float = FlutedGlass.presets[0].motion.frame,
    minPixelRatio: Float = FlutedGlass.presets[0].renderOptions.minPixelRatio,
    maxPixelCount: Int = FlutedGlass.presets[0].renderOptions.maxPixelCount,
    width: CGFloat? = FlutedGlass.presets[0].renderOptions.width,
    height: CGFloat? = FlutedGlass.presets[0].renderOptions.height,
    image: ShaderImage? = FlutedGlass.presets[0].image
  ) {
    self.init(
      params: FlutedGlassParams(
        colorBack: colorBack,
        colorShadow: colorShadow,
        colorHighlight: colorHighlight,
        shadows: shadows,
        size: size,
        angle: angle,
        distortion: distortion,
        shift: shift,
        blur: blur,
        edges: edges,
        marginLeft: marginLeft,
        marginRight: marginRight,
        marginTop: marginTop,
        marginBottom: marginBottom,
        stretch: stretch,
        distortionShape: distortionShape,
        highlights: highlights,
        shape: shape,
        grainMixer: grainMixer,
        grainOverlay: grainOverlay
      ),
      sizing: ShaderSizingParams(
        fit: fit, scale: scale, rotation: rotation, originX: originX, originY: originY,
        offsetX: offsetX, offsetY: offsetY, worldWidth: worldWidth, worldHeight: worldHeight),
      motion: ShaderMotionParams(speed: speed, frame: frame),
      renderOptions: ShaderRenderOptions(
        minPixelRatio: minPixelRatio, maxPixelCount: maxPixelCount, width: width, height: height),
      image: image
    )
  }
}

extension Water {
  public init(
    colorBack: ShaderColor = Water.presets[0].params.colorBack,
    colorHighlight: ShaderColor = Water.presets[0].params.colorHighlight,
    highlights: Float = Water.presets[0].params.highlights,
    layering: Float = Water.presets[0].params.layering,
    edges: Float = Water.presets[0].params.edges,
    caustic: Float = Water.presets[0].params.caustic,
    waves: Float = Water.presets[0].params.waves,
    size: Float = Water.presets[0].params.size,
    fit: ShaderFit = Water.presets[0].sizing.fit,
    scale: Float = Water.presets[0].sizing.scale,
    rotation: Float = Water.presets[0].sizing.rotation,
    originX: Float = Water.presets[0].sizing.originX,
    originY: Float = Water.presets[0].sizing.originY,
    offsetX: Float = Water.presets[0].sizing.offsetX,
    offsetY: Float = Water.presets[0].sizing.offsetY,
    worldWidth: Float = Water.presets[0].sizing.worldWidth,
    worldHeight: Float = Water.presets[0].sizing.worldHeight,
    speed: Float = Water.presets[0].motion.speed,
    frame: Float = Water.presets[0].motion.frame,
    minPixelRatio: Float = Water.presets[0].renderOptions.minPixelRatio,
    maxPixelCount: Int = Water.presets[0].renderOptions.maxPixelCount,
    width: CGFloat? = Water.presets[0].renderOptions.width,
    height: CGFloat? = Water.presets[0].renderOptions.height,
    image: ShaderImage? = Water.presets[0].image
  ) {
    self.init(
      params: WaterParams(
        colorBack: colorBack,
        colorHighlight: colorHighlight,
        highlights: highlights,
        layering: layering,
        edges: edges,
        caustic: caustic,
        waves: waves,
        size: size
      ),
      sizing: ShaderSizingParams(
        fit: fit, scale: scale, rotation: rotation, originX: originX, originY: originY,
        offsetX: offsetX, offsetY: offsetY, worldWidth: worldWidth, worldHeight: worldHeight),
      motion: ShaderMotionParams(speed: speed, frame: frame),
      renderOptions: ShaderRenderOptions(
        minPixelRatio: minPixelRatio, maxPixelCount: maxPixelCount, width: width, height: height),
      image: image
    )
  }
}

extension ImageDithering {
  public init(
    colorFront: ShaderColor = ImageDithering.presets[0].params.colorFront,
    colorBack: ShaderColor = ImageDithering.presets[0].params.colorBack,
    colorHighlight: ShaderColor = ImageDithering.presets[0].params.colorHighlight,
    type: DitheringType = ImageDithering.presets[0].params.type,
    size: Float = ImageDithering.presets[0].params.size,
    colorSteps: Float = ImageDithering.presets[0].params.colorSteps,
    originalColors: Float = ImageDithering.presets[0].params.originalColors,
    inverted: Float = ImageDithering.presets[0].params.inverted,
    fit: ShaderFit = ImageDithering.presets[0].sizing.fit,
    scale: Float = ImageDithering.presets[0].sizing.scale,
    rotation: Float = ImageDithering.presets[0].sizing.rotation,
    originX: Float = ImageDithering.presets[0].sizing.originX,
    originY: Float = ImageDithering.presets[0].sizing.originY,
    offsetX: Float = ImageDithering.presets[0].sizing.offsetX,
    offsetY: Float = ImageDithering.presets[0].sizing.offsetY,
    worldWidth: Float = ImageDithering.presets[0].sizing.worldWidth,
    worldHeight: Float = ImageDithering.presets[0].sizing.worldHeight,
    speed: Float = ImageDithering.presets[0].motion.speed,
    frame: Float = ImageDithering.presets[0].motion.frame,
    minPixelRatio: Float = ImageDithering.presets[0].renderOptions.minPixelRatio,
    maxPixelCount: Int = ImageDithering.presets[0].renderOptions.maxPixelCount,
    width: CGFloat? = ImageDithering.presets[0].renderOptions.width,
    height: CGFloat? = ImageDithering.presets[0].renderOptions.height,
    image: ShaderImage? = ImageDithering.presets[0].image
  ) {
    self.init(
      params: ImageDitheringParams(
        colorFront: colorFront,
        colorBack: colorBack,
        colorHighlight: colorHighlight,
        type: type,
        size: size,
        colorSteps: colorSteps,
        originalColors: originalColors,
        inverted: inverted
      ),
      sizing: ShaderSizingParams(
        fit: fit, scale: scale, rotation: rotation, originX: originX, originY: originY,
        offsetX: offsetX, offsetY: offsetY, worldWidth: worldWidth, worldHeight: worldHeight),
      motion: ShaderMotionParams(speed: speed, frame: frame),
      renderOptions: ShaderRenderOptions(
        minPixelRatio: minPixelRatio, maxPixelCount: maxPixelCount, width: width, height: height),
      image: image
    )
  }
}

extension Heatmap {
  public init(
    colorBack: ShaderColor = Heatmap.presets[0].params.colorBack,
    colors: [ShaderColor] = Heatmap.presets[0].params.colors,
    contour: Float = Heatmap.presets[0].params.contour,
    angle: Float = Heatmap.presets[0].params.angle,
    noise: Float = Heatmap.presets[0].params.noise,
    innerGlow: Float = Heatmap.presets[0].params.innerGlow,
    outerGlow: Float = Heatmap.presets[0].params.outerGlow,
    fit: ShaderFit = Heatmap.presets[0].sizing.fit,
    scale: Float = Heatmap.presets[0].sizing.scale,
    rotation: Float = Heatmap.presets[0].sizing.rotation,
    originX: Float = Heatmap.presets[0].sizing.originX,
    originY: Float = Heatmap.presets[0].sizing.originY,
    offsetX: Float = Heatmap.presets[0].sizing.offsetX,
    offsetY: Float = Heatmap.presets[0].sizing.offsetY,
    worldWidth: Float = Heatmap.presets[0].sizing.worldWidth,
    worldHeight: Float = Heatmap.presets[0].sizing.worldHeight,
    speed: Float = Heatmap.presets[0].motion.speed,
    frame: Float = Heatmap.presets[0].motion.frame,
    minPixelRatio: Float = Heatmap.presets[0].renderOptions.minPixelRatio,
    maxPixelCount: Int = Heatmap.presets[0].renderOptions.maxPixelCount,
    width: CGFloat? = Heatmap.presets[0].renderOptions.width,
    height: CGFloat? = Heatmap.presets[0].renderOptions.height,
    image: ShaderImage? = Heatmap.presets[0].image
  ) {
    self.init(
      params: HeatmapParams(
        colorBack: colorBack,
        colors: colors,
        contour: contour,
        angle: angle,
        noise: noise,
        innerGlow: innerGlow,
        outerGlow: outerGlow
      ),
      sizing: ShaderSizingParams(
        fit: fit, scale: scale, rotation: rotation, originX: originX, originY: originY,
        offsetX: offsetX, offsetY: offsetY, worldWidth: worldWidth, worldHeight: worldHeight),
      motion: ShaderMotionParams(speed: speed, frame: frame),
      renderOptions: ShaderRenderOptions(
        minPixelRatio: minPixelRatio, maxPixelCount: maxPixelCount, width: width, height: height),
      image: image
    )
  }
}

extension LiquidMetal {
  public init(
    colorBack: ShaderColor = LiquidMetal.presets[0].params.colorBack,
    colorTint: ShaderColor = LiquidMetal.presets[0].params.colorTint,
    repetition: Float = LiquidMetal.presets[0].params.repetition,
    softness: Float = LiquidMetal.presets[0].params.softness,
    shiftRed: Float = LiquidMetal.presets[0].params.shiftRed,
    shiftBlue: Float = LiquidMetal.presets[0].params.shiftBlue,
    distortion: Float = LiquidMetal.presets[0].params.distortion,
    contour: Float = LiquidMetal.presets[0].params.contour,
    angle: Float = LiquidMetal.presets[0].params.angle,
    shape: LiquidMetalShape = LiquidMetal.presets[0].params.shape,
    fit: ShaderFit = LiquidMetal.presets[0].sizing.fit,
    scale: Float = LiquidMetal.presets[0].sizing.scale,
    rotation: Float = LiquidMetal.presets[0].sizing.rotation,
    originX: Float = LiquidMetal.presets[0].sizing.originX,
    originY: Float = LiquidMetal.presets[0].sizing.originY,
    offsetX: Float = LiquidMetal.presets[0].sizing.offsetX,
    offsetY: Float = LiquidMetal.presets[0].sizing.offsetY,
    worldWidth: Float = LiquidMetal.presets[0].sizing.worldWidth,
    worldHeight: Float = LiquidMetal.presets[0].sizing.worldHeight,
    speed: Float = LiquidMetal.presets[0].motion.speed,
    frame: Float = LiquidMetal.presets[0].motion.frame,
    minPixelRatio: Float = LiquidMetal.presets[0].renderOptions.minPixelRatio,
    maxPixelCount: Int = LiquidMetal.presets[0].renderOptions.maxPixelCount,
    width: CGFloat? = LiquidMetal.presets[0].renderOptions.width,
    height: CGFloat? = LiquidMetal.presets[0].renderOptions.height,
    image: ShaderImage? = LiquidMetal.presets[0].image
  ) {
    self.init(
      params: LiquidMetalParams(
        colorBack: colorBack,
        colorTint: colorTint,
        repetition: repetition,
        softness: softness,
        shiftRed: shiftRed,
        shiftBlue: shiftBlue,
        distortion: distortion,
        contour: contour,
        angle: angle,
        shape: shape
      ),
      sizing: ShaderSizingParams(
        fit: fit, scale: scale, rotation: rotation, originX: originX, originY: originY,
        offsetX: offsetX, offsetY: offsetY, worldWidth: worldWidth, worldHeight: worldHeight),
      motion: ShaderMotionParams(speed: speed, frame: frame),
      renderOptions: ShaderRenderOptions(
        minPixelRatio: minPixelRatio, maxPixelCount: maxPixelCount, width: width, height: height),
      image: image
    )
  }
}

extension HalftoneDots {
  public init(
    colorFront: ShaderColor = HalftoneDots.presets[0].params.colorFront,
    colorBack: ShaderColor = HalftoneDots.presets[0].params.colorBack,
    size: Float = HalftoneDots.presets[0].params.size,
    grid: HalftoneDotsGrid = HalftoneDots.presets[0].params.grid,
    radius: Float = HalftoneDots.presets[0].params.radius,
    contrast: Float = HalftoneDots.presets[0].params.contrast,
    originalColors: Float = HalftoneDots.presets[0].params.originalColors,
    inverted: Float = HalftoneDots.presets[0].params.inverted,
    grainMixer: Float = HalftoneDots.presets[0].params.grainMixer,
    grainOverlay: Float = HalftoneDots.presets[0].params.grainOverlay,
    grainSize: Float = HalftoneDots.presets[0].params.grainSize,
    type: HalftoneDotsType = HalftoneDots.presets[0].params.type,
    fit: ShaderFit = HalftoneDots.presets[0].sizing.fit,
    scale: Float = HalftoneDots.presets[0].sizing.scale,
    rotation: Float = HalftoneDots.presets[0].sizing.rotation,
    originX: Float = HalftoneDots.presets[0].sizing.originX,
    originY: Float = HalftoneDots.presets[0].sizing.originY,
    offsetX: Float = HalftoneDots.presets[0].sizing.offsetX,
    offsetY: Float = HalftoneDots.presets[0].sizing.offsetY,
    worldWidth: Float = HalftoneDots.presets[0].sizing.worldWidth,
    worldHeight: Float = HalftoneDots.presets[0].sizing.worldHeight,
    speed: Float = HalftoneDots.presets[0].motion.speed,
    frame: Float = HalftoneDots.presets[0].motion.frame,
    minPixelRatio: Float = HalftoneDots.presets[0].renderOptions.minPixelRatio,
    maxPixelCount: Int = HalftoneDots.presets[0].renderOptions.maxPixelCount,
    width: CGFloat? = HalftoneDots.presets[0].renderOptions.width,
    height: CGFloat? = HalftoneDots.presets[0].renderOptions.height,
    image: ShaderImage? = HalftoneDots.presets[0].image
  ) {
    self.init(
      params: HalftoneDotsParams(
        colorFront: colorFront,
        colorBack: colorBack,
        size: size,
        grid: grid,
        radius: radius,
        contrast: contrast,
        originalColors: originalColors,
        inverted: inverted,
        grainMixer: grainMixer,
        grainOverlay: grainOverlay,
        grainSize: grainSize,
        type: type
      ),
      sizing: ShaderSizingParams(
        fit: fit, scale: scale, rotation: rotation, originX: originX, originY: originY,
        offsetX: offsetX, offsetY: offsetY, worldWidth: worldWidth, worldHeight: worldHeight),
      motion: ShaderMotionParams(speed: speed, frame: frame),
      renderOptions: ShaderRenderOptions(
        minPixelRatio: minPixelRatio, maxPixelCount: maxPixelCount, width: width, height: height),
      image: image
    )
  }
}

extension HalftoneCmyk {
  public init(
    colorBack: ShaderColor = HalftoneCmyk.presets[0].params.colorBack,
    colorC: ShaderColor = HalftoneCmyk.presets[0].params.colorC,
    colorM: ShaderColor = HalftoneCmyk.presets[0].params.colorM,
    colorY: ShaderColor = HalftoneCmyk.presets[0].params.colorY,
    colorK: ShaderColor = HalftoneCmyk.presets[0].params.colorK,
    size: Float = HalftoneCmyk.presets[0].params.size,
    contrast: Float = HalftoneCmyk.presets[0].params.contrast,
    softness: Float = HalftoneCmyk.presets[0].params.softness,
    grainSize: Float = HalftoneCmyk.presets[0].params.grainSize,
    grainMixer: Float = HalftoneCmyk.presets[0].params.grainMixer,
    grainOverlay: Float = HalftoneCmyk.presets[0].params.grainOverlay,
    gridNoise: Float = HalftoneCmyk.presets[0].params.gridNoise,
    floodC: Float = HalftoneCmyk.presets[0].params.floodC,
    floodM: Float = HalftoneCmyk.presets[0].params.floodM,
    floodY: Float = HalftoneCmyk.presets[0].params.floodY,
    floodK: Float = HalftoneCmyk.presets[0].params.floodK,
    gainC: Float = HalftoneCmyk.presets[0].params.gainC,
    gainM: Float = HalftoneCmyk.presets[0].params.gainM,
    gainY: Float = HalftoneCmyk.presets[0].params.gainY,
    gainK: Float = HalftoneCmyk.presets[0].params.gainK,
    type: HalftoneCmykType = HalftoneCmyk.presets[0].params.type,
    fit: ShaderFit = HalftoneCmyk.presets[0].sizing.fit,
    scale: Float = HalftoneCmyk.presets[0].sizing.scale,
    rotation: Float = HalftoneCmyk.presets[0].sizing.rotation,
    originX: Float = HalftoneCmyk.presets[0].sizing.originX,
    originY: Float = HalftoneCmyk.presets[0].sizing.originY,
    offsetX: Float = HalftoneCmyk.presets[0].sizing.offsetX,
    offsetY: Float = HalftoneCmyk.presets[0].sizing.offsetY,
    worldWidth: Float = HalftoneCmyk.presets[0].sizing.worldWidth,
    worldHeight: Float = HalftoneCmyk.presets[0].sizing.worldHeight,
    speed: Float = HalftoneCmyk.presets[0].motion.speed,
    frame: Float = HalftoneCmyk.presets[0].motion.frame,
    minPixelRatio: Float = HalftoneCmyk.presets[0].renderOptions.minPixelRatio,
    maxPixelCount: Int = HalftoneCmyk.presets[0].renderOptions.maxPixelCount,
    width: CGFloat? = HalftoneCmyk.presets[0].renderOptions.width,
    height: CGFloat? = HalftoneCmyk.presets[0].renderOptions.height,
    image: ShaderImage? = HalftoneCmyk.presets[0].image
  ) {
    self.init(
      params: HalftoneCmykParams(
        colorBack: colorBack,
        colorC: colorC,
        colorM: colorM,
        colorY: colorY,
        colorK: colorK,
        size: size,
        contrast: contrast,
        softness: softness,
        grainSize: grainSize,
        grainMixer: grainMixer,
        grainOverlay: grainOverlay,
        gridNoise: gridNoise,
        floodC: floodC,
        floodM: floodM,
        floodY: floodY,
        floodK: floodK,
        gainC: gainC,
        gainM: gainM,
        gainY: gainY,
        gainK: gainK,
        type: type
      ),
      sizing: ShaderSizingParams(
        fit: fit, scale: scale, rotation: rotation, originX: originX, originY: originY,
        offsetX: offsetX, offsetY: offsetY, worldWidth: worldWidth, worldHeight: worldHeight),
      motion: ShaderMotionParams(speed: speed, frame: frame),
      renderOptions: ShaderRenderOptions(
        minPixelRatio: minPixelRatio, maxPixelCount: maxPixelCount, width: width, height: height),
      image: image
    )
  }
}

extension GemSmoke {
  public init(
    colors: [ShaderColor] = GemSmoke.presets[0].params.colors,
    colorBack: ShaderColor = GemSmoke.presets[0].params.colorBack,
    colorInner: ShaderColor = GemSmoke.presets[0].params.colorInner,
    innerDistortion: Float = GemSmoke.presets[0].params.innerDistortion,
    outerDistortion: Float = GemSmoke.presets[0].params.outerDistortion,
    outerGlow: Float = GemSmoke.presets[0].params.outerGlow,
    innerGlow: Float = GemSmoke.presets[0].params.innerGlow,
    offset: Float = GemSmoke.presets[0].params.offset,
    angle: Float = GemSmoke.presets[0].params.angle,
    size: Float = GemSmoke.presets[0].params.size,
    shape: GemSmokeShape = GemSmoke.presets[0].params.shape,
    fit: ShaderFit = GemSmoke.presets[0].sizing.fit,
    scale: Float = GemSmoke.presets[0].sizing.scale,
    rotation: Float = GemSmoke.presets[0].sizing.rotation,
    originX: Float = GemSmoke.presets[0].sizing.originX,
    originY: Float = GemSmoke.presets[0].sizing.originY,
    offsetX: Float = GemSmoke.presets[0].sizing.offsetX,
    offsetY: Float = GemSmoke.presets[0].sizing.offsetY,
    worldWidth: Float = GemSmoke.presets[0].sizing.worldWidth,
    worldHeight: Float = GemSmoke.presets[0].sizing.worldHeight,
    speed: Float = GemSmoke.presets[0].motion.speed,
    frame: Float = GemSmoke.presets[0].motion.frame,
    minPixelRatio: Float = GemSmoke.presets[0].renderOptions.minPixelRatio,
    maxPixelCount: Int = GemSmoke.presets[0].renderOptions.maxPixelCount,
    width: CGFloat? = GemSmoke.presets[0].renderOptions.width,
    height: CGFloat? = GemSmoke.presets[0].renderOptions.height,
    image: ShaderImage? = GemSmoke.presets[0].image
  ) {
    self.init(
      params: GemSmokeParams(
        colors: colors,
        colorBack: colorBack,
        colorInner: colorInner,
        innerDistortion: innerDistortion,
        outerDistortion: outerDistortion,
        outerGlow: outerGlow,
        innerGlow: innerGlow,
        offset: offset,
        angle: angle,
        size: size,
        shape: shape
      ),
      sizing: ShaderSizingParams(
        fit: fit, scale: scale, rotation: rotation, originX: originX, originY: originY,
        offsetX: offsetX, offsetY: offsetY, worldWidth: worldWidth, worldHeight: worldHeight),
      motion: ShaderMotionParams(speed: speed, frame: frame),
      renderOptions: ShaderRenderOptions(
        minPixelRatio: minPixelRatio, maxPixelCount: maxPixelCount, width: width, height: height),
      image: image
    )
  }
}
