import CoreGraphics

// Generated by Scripts/generate-swift-component-initializers.mjs.
extension MeshGradient {
  public init(
    colors: [ShaderColor] = MeshGradientPreset.default.params.colors,
    distortion: Float = MeshGradientPreset.default.params.distortion,
    swirl: Float = MeshGradientPreset.default.params.swirl,
    grainMixer: Float = MeshGradientPreset.default.params.grainMixer,
    grainOverlay: Float = MeshGradientPreset.default.params.grainOverlay,
    fit: ShaderFit = MeshGradientPreset.default.sizing.fit,
    scale: Float = MeshGradientPreset.default.sizing.scale,
    rotation: Float = MeshGradientPreset.default.sizing.rotation,
    originX: Float = MeshGradientPreset.default.sizing.originX,
    originY: Float = MeshGradientPreset.default.sizing.originY,
    offsetX: Float = MeshGradientPreset.default.sizing.offsetX,
    offsetY: Float = MeshGradientPreset.default.sizing.offsetY,
    worldWidth: Float = MeshGradientPreset.default.sizing.worldWidth,
    worldHeight: Float = MeshGradientPreset.default.sizing.worldHeight,
    speed: Float = MeshGradientPreset.default.motion.speed,
    frame: Float = MeshGradientPreset.default.motion.frame,
    minPixelRatio: Float = MeshGradientPreset.default.renderOptions.minPixelRatio,
    maxPixelCount: Int = MeshGradientPreset.default.renderOptions.maxPixelCount,
    width: CGFloat? = MeshGradientPreset.default.renderOptions.width,
    height: CGFloat? = MeshGradientPreset.default.renderOptions.height,
    image: ShaderImage? = MeshGradientPreset.default.image
  ) {
    self.init(
      params: MeshGradientParams(
        colors: colors,
        distortion: distortion,
        swirl: swirl,
        grainMixer: grainMixer,
        grainOverlay: grainOverlay
      ),
      sizing: ShaderSizingParams(
        fit: fit, scale: scale, rotation: rotation, originX: originX, originY: originY,
        offsetX: offsetX, offsetY: offsetY, worldWidth: worldWidth, worldHeight: worldHeight),
      motion: ShaderMotionParams(speed: speed, frame: frame),
      renderOptions: ShaderRenderOptions(
        minPixelRatio: minPixelRatio, maxPixelCount: maxPixelCount, width: width, height: height),
      image: image
    )
  }
}

extension SmokeRing {
  public init(
    colorBack: ShaderColor = SmokeRingPreset.default.params.colorBack,
    colors: [ShaderColor] = SmokeRingPreset.default.params.colors,
    noiseScale: Float = SmokeRingPreset.default.params.noiseScale,
    thickness: Float = SmokeRingPreset.default.params.thickness,
    radius: Float = SmokeRingPreset.default.params.radius,
    innerShape: Float = SmokeRingPreset.default.params.innerShape,
    noiseIterations: Float = SmokeRingPreset.default.params.noiseIterations,
    fit: ShaderFit = SmokeRingPreset.default.sizing.fit,
    scale: Float = SmokeRingPreset.default.sizing.scale,
    rotation: Float = SmokeRingPreset.default.sizing.rotation,
    originX: Float = SmokeRingPreset.default.sizing.originX,
    originY: Float = SmokeRingPreset.default.sizing.originY,
    offsetX: Float = SmokeRingPreset.default.sizing.offsetX,
    offsetY: Float = SmokeRingPreset.default.sizing.offsetY,
    worldWidth: Float = SmokeRingPreset.default.sizing.worldWidth,
    worldHeight: Float = SmokeRingPreset.default.sizing.worldHeight,
    speed: Float = SmokeRingPreset.default.motion.speed,
    frame: Float = SmokeRingPreset.default.motion.frame,
    minPixelRatio: Float = SmokeRingPreset.default.renderOptions.minPixelRatio,
    maxPixelCount: Int = SmokeRingPreset.default.renderOptions.maxPixelCount,
    width: CGFloat? = SmokeRingPreset.default.renderOptions.width,
    height: CGFloat? = SmokeRingPreset.default.renderOptions.height,
    image: ShaderImage? = SmokeRingPreset.default.image
  ) {
    self.init(
      params: SmokeRingParams(
        colorBack: colorBack,
        colors: colors,
        noiseScale: noiseScale,
        thickness: thickness,
        radius: radius,
        innerShape: innerShape,
        noiseIterations: noiseIterations
      ),
      sizing: ShaderSizingParams(
        fit: fit, scale: scale, rotation: rotation, originX: originX, originY: originY,
        offsetX: offsetX, offsetY: offsetY, worldWidth: worldWidth, worldHeight: worldHeight),
      motion: ShaderMotionParams(speed: speed, frame: frame),
      renderOptions: ShaderRenderOptions(
        minPixelRatio: minPixelRatio, maxPixelCount: maxPixelCount, width: width, height: height),
      image: image
    )
  }
}

extension NeuroNoise {
  public init(
    colorFront: ShaderColor = NeuroNoisePreset.default.params.colorFront,
    colorMid: ShaderColor = NeuroNoisePreset.default.params.colorMid,
    colorBack: ShaderColor = NeuroNoisePreset.default.params.colorBack,
    brightness: Float = NeuroNoisePreset.default.params.brightness,
    contrast: Float = NeuroNoisePreset.default.params.contrast,
    fit: ShaderFit = NeuroNoisePreset.default.sizing.fit,
    scale: Float = NeuroNoisePreset.default.sizing.scale,
    rotation: Float = NeuroNoisePreset.default.sizing.rotation,
    originX: Float = NeuroNoisePreset.default.sizing.originX,
    originY: Float = NeuroNoisePreset.default.sizing.originY,
    offsetX: Float = NeuroNoisePreset.default.sizing.offsetX,
    offsetY: Float = NeuroNoisePreset.default.sizing.offsetY,
    worldWidth: Float = NeuroNoisePreset.default.sizing.worldWidth,
    worldHeight: Float = NeuroNoisePreset.default.sizing.worldHeight,
    speed: Float = NeuroNoisePreset.default.motion.speed,
    frame: Float = NeuroNoisePreset.default.motion.frame,
    minPixelRatio: Float = NeuroNoisePreset.default.renderOptions.minPixelRatio,
    maxPixelCount: Int = NeuroNoisePreset.default.renderOptions.maxPixelCount,
    width: CGFloat? = NeuroNoisePreset.default.renderOptions.width,
    height: CGFloat? = NeuroNoisePreset.default.renderOptions.height,
    image: ShaderImage? = NeuroNoisePreset.default.image
  ) {
    self.init(
      params: NeuroNoiseParams(
        colorFront: colorFront,
        colorMid: colorMid,
        colorBack: colorBack,
        brightness: brightness,
        contrast: contrast
      ),
      sizing: ShaderSizingParams(
        fit: fit, scale: scale, rotation: rotation, originX: originX, originY: originY,
        offsetX: offsetX, offsetY: offsetY, worldWidth: worldWidth, worldHeight: worldHeight),
      motion: ShaderMotionParams(speed: speed, frame: frame),
      renderOptions: ShaderRenderOptions(
        minPixelRatio: minPixelRatio, maxPixelCount: maxPixelCount, width: width, height: height),
      image: image
    )
  }
}

extension DotOrbit {
  public init(
    colorBack: ShaderColor = DotOrbitPreset.default.params.colorBack,
    colors: [ShaderColor] = DotOrbitPreset.default.params.colors,
    stepsPerColor: Float = DotOrbitPreset.default.params.stepsPerColor,
    size: Float = DotOrbitPreset.default.params.size,
    sizeRange: Float = DotOrbitPreset.default.params.sizeRange,
    spreading: Float = DotOrbitPreset.default.params.spreading,
    fit: ShaderFit = DotOrbitPreset.default.sizing.fit,
    scale: Float = DotOrbitPreset.default.sizing.scale,
    rotation: Float = DotOrbitPreset.default.sizing.rotation,
    originX: Float = DotOrbitPreset.default.sizing.originX,
    originY: Float = DotOrbitPreset.default.sizing.originY,
    offsetX: Float = DotOrbitPreset.default.sizing.offsetX,
    offsetY: Float = DotOrbitPreset.default.sizing.offsetY,
    worldWidth: Float = DotOrbitPreset.default.sizing.worldWidth,
    worldHeight: Float = DotOrbitPreset.default.sizing.worldHeight,
    speed: Float = DotOrbitPreset.default.motion.speed,
    frame: Float = DotOrbitPreset.default.motion.frame,
    minPixelRatio: Float = DotOrbitPreset.default.renderOptions.minPixelRatio,
    maxPixelCount: Int = DotOrbitPreset.default.renderOptions.maxPixelCount,
    width: CGFloat? = DotOrbitPreset.default.renderOptions.width,
    height: CGFloat? = DotOrbitPreset.default.renderOptions.height,
    image: ShaderImage? = DotOrbitPreset.default.image
  ) {
    self.init(
      params: DotOrbitParams(
        colorBack: colorBack,
        colors: colors,
        stepsPerColor: stepsPerColor,
        size: size,
        sizeRange: sizeRange,
        spreading: spreading
      ),
      sizing: ShaderSizingParams(
        fit: fit, scale: scale, rotation: rotation, originX: originX, originY: originY,
        offsetX: offsetX, offsetY: offsetY, worldWidth: worldWidth, worldHeight: worldHeight),
      motion: ShaderMotionParams(speed: speed, frame: frame),
      renderOptions: ShaderRenderOptions(
        minPixelRatio: minPixelRatio, maxPixelCount: maxPixelCount, width: width, height: height),
      image: image
    )
  }
}

extension DotGrid {
  public init(
    colorBack: ShaderColor = DotGridPreset.default.params.colorBack,
    colorFill: ShaderColor = DotGridPreset.default.params.colorFill,
    colorStroke: ShaderColor = DotGridPreset.default.params.colorStroke,
    dotSize: Float = DotGridPreset.default.params.dotSize,
    gapX: Float = DotGridPreset.default.params.gapX,
    gapY: Float = DotGridPreset.default.params.gapY,
    strokeWidth: Float = DotGridPreset.default.params.strokeWidth,
    sizeRange: Float = DotGridPreset.default.params.sizeRange,
    opacityRange: Float = DotGridPreset.default.params.opacityRange,
    shape: DotGridShape = DotGridPreset.default.params.shape,
    fit: ShaderFit = DotGridPreset.default.sizing.fit,
    scale: Float = DotGridPreset.default.sizing.scale,
    rotation: Float = DotGridPreset.default.sizing.rotation,
    originX: Float = DotGridPreset.default.sizing.originX,
    originY: Float = DotGridPreset.default.sizing.originY,
    offsetX: Float = DotGridPreset.default.sizing.offsetX,
    offsetY: Float = DotGridPreset.default.sizing.offsetY,
    worldWidth: Float = DotGridPreset.default.sizing.worldWidth,
    worldHeight: Float = DotGridPreset.default.sizing.worldHeight,
    speed: Float = DotGridPreset.default.motion.speed,
    frame: Float = DotGridPreset.default.motion.frame,
    minPixelRatio: Float = DotGridPreset.default.renderOptions.minPixelRatio,
    maxPixelCount: Int = DotGridPreset.default.renderOptions.maxPixelCount,
    width: CGFloat? = DotGridPreset.default.renderOptions.width,
    height: CGFloat? = DotGridPreset.default.renderOptions.height,
    image: ShaderImage? = DotGridPreset.default.image
  ) {
    self.init(
      params: DotGridParams(
        colorBack: colorBack,
        colorFill: colorFill,
        colorStroke: colorStroke,
        dotSize: dotSize,
        gapX: gapX,
        gapY: gapY,
        strokeWidth: strokeWidth,
        sizeRange: sizeRange,
        opacityRange: opacityRange,
        shape: shape
      ),
      sizing: ShaderSizingParams(
        fit: fit, scale: scale, rotation: rotation, originX: originX, originY: originY,
        offsetX: offsetX, offsetY: offsetY, worldWidth: worldWidth, worldHeight: worldHeight),
      motion: ShaderMotionParams(speed: speed, frame: frame),
      renderOptions: ShaderRenderOptions(
        minPixelRatio: minPixelRatio, maxPixelCount: maxPixelCount, width: width, height: height),
      image: image
    )
  }
}

extension SimplexNoise {
  public init(
    colors: [ShaderColor] = SimplexNoisePreset.default.params.colors,
    stepsPerColor: Float = SimplexNoisePreset.default.params.stepsPerColor,
    softness: Float = SimplexNoisePreset.default.params.softness,
    fit: ShaderFit = SimplexNoisePreset.default.sizing.fit,
    scale: Float = SimplexNoisePreset.default.sizing.scale,
    rotation: Float = SimplexNoisePreset.default.sizing.rotation,
    originX: Float = SimplexNoisePreset.default.sizing.originX,
    originY: Float = SimplexNoisePreset.default.sizing.originY,
    offsetX: Float = SimplexNoisePreset.default.sizing.offsetX,
    offsetY: Float = SimplexNoisePreset.default.sizing.offsetY,
    worldWidth: Float = SimplexNoisePreset.default.sizing.worldWidth,
    worldHeight: Float = SimplexNoisePreset.default.sizing.worldHeight,
    speed: Float = SimplexNoisePreset.default.motion.speed,
    frame: Float = SimplexNoisePreset.default.motion.frame,
    minPixelRatio: Float = SimplexNoisePreset.default.renderOptions.minPixelRatio,
    maxPixelCount: Int = SimplexNoisePreset.default.renderOptions.maxPixelCount,
    width: CGFloat? = SimplexNoisePreset.default.renderOptions.width,
    height: CGFloat? = SimplexNoisePreset.default.renderOptions.height,
    image: ShaderImage? = SimplexNoisePreset.default.image
  ) {
    self.init(
      params: SimplexNoiseParams(
        colors: colors,
        stepsPerColor: stepsPerColor,
        softness: softness
      ),
      sizing: ShaderSizingParams(
        fit: fit, scale: scale, rotation: rotation, originX: originX, originY: originY,
        offsetX: offsetX, offsetY: offsetY, worldWidth: worldWidth, worldHeight: worldHeight),
      motion: ShaderMotionParams(speed: speed, frame: frame),
      renderOptions: ShaderRenderOptions(
        minPixelRatio: minPixelRatio, maxPixelCount: maxPixelCount, width: width, height: height),
      image: image
    )
  }
}

extension Metaballs {
  public init(
    colorBack: ShaderColor = MetaballsPreset.default.params.colorBack,
    colors: [ShaderColor] = MetaballsPreset.default.params.colors,
    count: Float = MetaballsPreset.default.params.count,
    size: Float = MetaballsPreset.default.params.size,
    sizeRange: Float = MetaballsPreset.default.params.sizeRange,
    fit: ShaderFit = MetaballsPreset.default.sizing.fit,
    scale: Float = MetaballsPreset.default.sizing.scale,
    rotation: Float = MetaballsPreset.default.sizing.rotation,
    originX: Float = MetaballsPreset.default.sizing.originX,
    originY: Float = MetaballsPreset.default.sizing.originY,
    offsetX: Float = MetaballsPreset.default.sizing.offsetX,
    offsetY: Float = MetaballsPreset.default.sizing.offsetY,
    worldWidth: Float = MetaballsPreset.default.sizing.worldWidth,
    worldHeight: Float = MetaballsPreset.default.sizing.worldHeight,
    speed: Float = MetaballsPreset.default.motion.speed,
    frame: Float = MetaballsPreset.default.motion.frame,
    minPixelRatio: Float = MetaballsPreset.default.renderOptions.minPixelRatio,
    maxPixelCount: Int = MetaballsPreset.default.renderOptions.maxPixelCount,
    width: CGFloat? = MetaballsPreset.default.renderOptions.width,
    height: CGFloat? = MetaballsPreset.default.renderOptions.height,
    image: ShaderImage? = MetaballsPreset.default.image
  ) {
    self.init(
      params: MetaballsParams(
        colorBack: colorBack,
        colors: colors,
        count: count,
        size: size,
        sizeRange: sizeRange
      ),
      sizing: ShaderSizingParams(
        fit: fit, scale: scale, rotation: rotation, originX: originX, originY: originY,
        offsetX: offsetX, offsetY: offsetY, worldWidth: worldWidth, worldHeight: worldHeight),
      motion: ShaderMotionParams(speed: speed, frame: frame),
      renderOptions: ShaderRenderOptions(
        minPixelRatio: minPixelRatio, maxPixelCount: maxPixelCount, width: width, height: height),
      image: image
    )
  }
}

extension Waves {
  public init(
    colorFront: ShaderColor = WavesPreset.default.params.colorFront,
    colorBack: ShaderColor = WavesPreset.default.params.colorBack,
    shape: Float = WavesPreset.default.params.shape,
    frequency: Float = WavesPreset.default.params.frequency,
    amplitude: Float = WavesPreset.default.params.amplitude,
    spacing: Float = WavesPreset.default.params.spacing,
    proportion: Float = WavesPreset.default.params.proportion,
    softness: Float = WavesPreset.default.params.softness,
    fit: ShaderFit = WavesPreset.default.sizing.fit,
    scale: Float = WavesPreset.default.sizing.scale,
    rotation: Float = WavesPreset.default.sizing.rotation,
    originX: Float = WavesPreset.default.sizing.originX,
    originY: Float = WavesPreset.default.sizing.originY,
    offsetX: Float = WavesPreset.default.sizing.offsetX,
    offsetY: Float = WavesPreset.default.sizing.offsetY,
    worldWidth: Float = WavesPreset.default.sizing.worldWidth,
    worldHeight: Float = WavesPreset.default.sizing.worldHeight,
    speed: Float = WavesPreset.default.motion.speed,
    frame: Float = WavesPreset.default.motion.frame,
    minPixelRatio: Float = WavesPreset.default.renderOptions.minPixelRatio,
    maxPixelCount: Int = WavesPreset.default.renderOptions.maxPixelCount,
    width: CGFloat? = WavesPreset.default.renderOptions.width,
    height: CGFloat? = WavesPreset.default.renderOptions.height,
    image: ShaderImage? = WavesPreset.default.image
  ) {
    self.init(
      params: WavesParams(
        colorFront: colorFront,
        colorBack: colorBack,
        shape: shape,
        frequency: frequency,
        amplitude: amplitude,
        spacing: spacing,
        proportion: proportion,
        softness: softness
      ),
      sizing: ShaderSizingParams(
        fit: fit, scale: scale, rotation: rotation, originX: originX, originY: originY,
        offsetX: offsetX, offsetY: offsetY, worldWidth: worldWidth, worldHeight: worldHeight),
      motion: ShaderMotionParams(speed: speed, frame: frame),
      renderOptions: ShaderRenderOptions(
        minPixelRatio: minPixelRatio, maxPixelCount: maxPixelCount, width: width, height: height),
      image: image
    )
  }
}

extension PerlinNoise {
  public init(
    colorFront: ShaderColor = PerlinNoisePreset.default.params.colorFront,
    colorBack: ShaderColor = PerlinNoisePreset.default.params.colorBack,
    proportion: Float = PerlinNoisePreset.default.params.proportion,
    softness: Float = PerlinNoisePreset.default.params.softness,
    octaveCount: Float = PerlinNoisePreset.default.params.octaveCount,
    persistence: Float = PerlinNoisePreset.default.params.persistence,
    lacunarity: Float = PerlinNoisePreset.default.params.lacunarity,
    fit: ShaderFit = PerlinNoisePreset.default.sizing.fit,
    scale: Float = PerlinNoisePreset.default.sizing.scale,
    rotation: Float = PerlinNoisePreset.default.sizing.rotation,
    originX: Float = PerlinNoisePreset.default.sizing.originX,
    originY: Float = PerlinNoisePreset.default.sizing.originY,
    offsetX: Float = PerlinNoisePreset.default.sizing.offsetX,
    offsetY: Float = PerlinNoisePreset.default.sizing.offsetY,
    worldWidth: Float = PerlinNoisePreset.default.sizing.worldWidth,
    worldHeight: Float = PerlinNoisePreset.default.sizing.worldHeight,
    speed: Float = PerlinNoisePreset.default.motion.speed,
    frame: Float = PerlinNoisePreset.default.motion.frame,
    minPixelRatio: Float = PerlinNoisePreset.default.renderOptions.minPixelRatio,
    maxPixelCount: Int = PerlinNoisePreset.default.renderOptions.maxPixelCount,
    width: CGFloat? = PerlinNoisePreset.default.renderOptions.width,
    height: CGFloat? = PerlinNoisePreset.default.renderOptions.height,
    image: ShaderImage? = PerlinNoisePreset.default.image
  ) {
    self.init(
      params: PerlinNoiseParams(
        colorFront: colorFront,
        colorBack: colorBack,
        proportion: proportion,
        softness: softness,
        octaveCount: octaveCount,
        persistence: persistence,
        lacunarity: lacunarity
      ),
      sizing: ShaderSizingParams(
        fit: fit, scale: scale, rotation: rotation, originX: originX, originY: originY,
        offsetX: offsetX, offsetY: offsetY, worldWidth: worldWidth, worldHeight: worldHeight),
      motion: ShaderMotionParams(speed: speed, frame: frame),
      renderOptions: ShaderRenderOptions(
        minPixelRatio: minPixelRatio, maxPixelCount: maxPixelCount, width: width, height: height),
      image: image
    )
  }
}

extension Voronoi {
  public init(
    colors: [ShaderColor] = VoronoiPreset.default.params.colors,
    stepsPerColor: Float = VoronoiPreset.default.params.stepsPerColor,
    colorGap: ShaderColor = VoronoiPreset.default.params.colorGap,
    colorGlow: ShaderColor = VoronoiPreset.default.params.colorGlow,
    distortion: Float = VoronoiPreset.default.params.distortion,
    gap: Float = VoronoiPreset.default.params.gap,
    glow: Float = VoronoiPreset.default.params.glow,
    fit: ShaderFit = VoronoiPreset.default.sizing.fit,
    scale: Float = VoronoiPreset.default.sizing.scale,
    rotation: Float = VoronoiPreset.default.sizing.rotation,
    originX: Float = VoronoiPreset.default.sizing.originX,
    originY: Float = VoronoiPreset.default.sizing.originY,
    offsetX: Float = VoronoiPreset.default.sizing.offsetX,
    offsetY: Float = VoronoiPreset.default.sizing.offsetY,
    worldWidth: Float = VoronoiPreset.default.sizing.worldWidth,
    worldHeight: Float = VoronoiPreset.default.sizing.worldHeight,
    speed: Float = VoronoiPreset.default.motion.speed,
    frame: Float = VoronoiPreset.default.motion.frame,
    minPixelRatio: Float = VoronoiPreset.default.renderOptions.minPixelRatio,
    maxPixelCount: Int = VoronoiPreset.default.renderOptions.maxPixelCount,
    width: CGFloat? = VoronoiPreset.default.renderOptions.width,
    height: CGFloat? = VoronoiPreset.default.renderOptions.height,
    image: ShaderImage? = VoronoiPreset.default.image
  ) {
    self.init(
      params: VoronoiParams(
        colors: colors,
        stepsPerColor: stepsPerColor,
        colorGap: colorGap,
        colorGlow: colorGlow,
        distortion: distortion,
        gap: gap,
        glow: glow
      ),
      sizing: ShaderSizingParams(
        fit: fit, scale: scale, rotation: rotation, originX: originX, originY: originY,
        offsetX: offsetX, offsetY: offsetY, worldWidth: worldWidth, worldHeight: worldHeight),
      motion: ShaderMotionParams(speed: speed, frame: frame),
      renderOptions: ShaderRenderOptions(
        minPixelRatio: minPixelRatio, maxPixelCount: maxPixelCount, width: width, height: height),
      image: image
    )
  }
}

extension Warp {
  public init(
    colors: [ShaderColor] = WarpPreset.default.params.colors,
    proportion: Float = WarpPreset.default.params.proportion,
    softness: Float = WarpPreset.default.params.softness,
    shape: WarpPattern = WarpPreset.default.params.shape,
    shapeScale: Float = WarpPreset.default.params.shapeScale,
    distortion: Float = WarpPreset.default.params.distortion,
    swirl: Float = WarpPreset.default.params.swirl,
    swirlIterations: Float = WarpPreset.default.params.swirlIterations,
    fit: ShaderFit = WarpPreset.default.sizing.fit,
    scale: Float = WarpPreset.default.sizing.scale,
    rotation: Float = WarpPreset.default.sizing.rotation,
    originX: Float = WarpPreset.default.sizing.originX,
    originY: Float = WarpPreset.default.sizing.originY,
    offsetX: Float = WarpPreset.default.sizing.offsetX,
    offsetY: Float = WarpPreset.default.sizing.offsetY,
    worldWidth: Float = WarpPreset.default.sizing.worldWidth,
    worldHeight: Float = WarpPreset.default.sizing.worldHeight,
    speed: Float = WarpPreset.default.motion.speed,
    frame: Float = WarpPreset.default.motion.frame,
    minPixelRatio: Float = WarpPreset.default.renderOptions.minPixelRatio,
    maxPixelCount: Int = WarpPreset.default.renderOptions.maxPixelCount,
    width: CGFloat? = WarpPreset.default.renderOptions.width,
    height: CGFloat? = WarpPreset.default.renderOptions.height,
    image: ShaderImage? = WarpPreset.default.image
  ) {
    self.init(
      params: WarpParams(
        colors: colors,
        proportion: proportion,
        softness: softness,
        shape: shape,
        shapeScale: shapeScale,
        distortion: distortion,
        swirl: swirl,
        swirlIterations: swirlIterations
      ),
      sizing: ShaderSizingParams(
        fit: fit, scale: scale, rotation: rotation, originX: originX, originY: originY,
        offsetX: offsetX, offsetY: offsetY, worldWidth: worldWidth, worldHeight: worldHeight),
      motion: ShaderMotionParams(speed: speed, frame: frame),
      renderOptions: ShaderRenderOptions(
        minPixelRatio: minPixelRatio, maxPixelCount: maxPixelCount, width: width, height: height),
      image: image
    )
  }
}

extension GodRays {
  public init(
    colorBack: ShaderColor = GodRaysPreset.default.params.colorBack,
    colorBloom: ShaderColor = GodRaysPreset.default.params.colorBloom,
    colors: [ShaderColor] = GodRaysPreset.default.params.colors,
    density: Float = GodRaysPreset.default.params.density,
    spotty: Float = GodRaysPreset.default.params.spotty,
    midSize: Float = GodRaysPreset.default.params.midSize,
    midIntensity: Float = GodRaysPreset.default.params.midIntensity,
    intensity: Float = GodRaysPreset.default.params.intensity,
    bloom: Float = GodRaysPreset.default.params.bloom,
    fit: ShaderFit = GodRaysPreset.default.sizing.fit,
    scale: Float = GodRaysPreset.default.sizing.scale,
    rotation: Float = GodRaysPreset.default.sizing.rotation,
    originX: Float = GodRaysPreset.default.sizing.originX,
    originY: Float = GodRaysPreset.default.sizing.originY,
    offsetX: Float = GodRaysPreset.default.sizing.offsetX,
    offsetY: Float = GodRaysPreset.default.sizing.offsetY,
    worldWidth: Float = GodRaysPreset.default.sizing.worldWidth,
    worldHeight: Float = GodRaysPreset.default.sizing.worldHeight,
    speed: Float = GodRaysPreset.default.motion.speed,
    frame: Float = GodRaysPreset.default.motion.frame,
    minPixelRatio: Float = GodRaysPreset.default.renderOptions.minPixelRatio,
    maxPixelCount: Int = GodRaysPreset.default.renderOptions.maxPixelCount,
    width: CGFloat? = GodRaysPreset.default.renderOptions.width,
    height: CGFloat? = GodRaysPreset.default.renderOptions.height,
    image: ShaderImage? = GodRaysPreset.default.image
  ) {
    self.init(
      params: GodRaysParams(
        colorBack: colorBack,
        colorBloom: colorBloom,
        colors: colors,
        density: density,
        spotty: spotty,
        midSize: midSize,
        midIntensity: midIntensity,
        intensity: intensity,
        bloom: bloom
      ),
      sizing: ShaderSizingParams(
        fit: fit, scale: scale, rotation: rotation, originX: originX, originY: originY,
        offsetX: offsetX, offsetY: offsetY, worldWidth: worldWidth, worldHeight: worldHeight),
      motion: ShaderMotionParams(speed: speed, frame: frame),
      renderOptions: ShaderRenderOptions(
        minPixelRatio: minPixelRatio, maxPixelCount: maxPixelCount, width: width, height: height),
      image: image
    )
  }
}

extension Spiral {
  public init(
    colorBack: ShaderColor = SpiralPreset.default.params.colorBack,
    colorFront: ShaderColor = SpiralPreset.default.params.colorFront,
    density: Float = SpiralPreset.default.params.density,
    distortion: Float = SpiralPreset.default.params.distortion,
    strokeWidth: Float = SpiralPreset.default.params.strokeWidth,
    strokeTaper: Float = SpiralPreset.default.params.strokeTaper,
    strokeCap: Float = SpiralPreset.default.params.strokeCap,
    noise: Float = SpiralPreset.default.params.noise,
    noiseFrequency: Float = SpiralPreset.default.params.noiseFrequency,
    softness: Float = SpiralPreset.default.params.softness,
    fit: ShaderFit = SpiralPreset.default.sizing.fit,
    scale: Float = SpiralPreset.default.sizing.scale,
    rotation: Float = SpiralPreset.default.sizing.rotation,
    originX: Float = SpiralPreset.default.sizing.originX,
    originY: Float = SpiralPreset.default.sizing.originY,
    offsetX: Float = SpiralPreset.default.sizing.offsetX,
    offsetY: Float = SpiralPreset.default.sizing.offsetY,
    worldWidth: Float = SpiralPreset.default.sizing.worldWidth,
    worldHeight: Float = SpiralPreset.default.sizing.worldHeight,
    speed: Float = SpiralPreset.default.motion.speed,
    frame: Float = SpiralPreset.default.motion.frame,
    minPixelRatio: Float = SpiralPreset.default.renderOptions.minPixelRatio,
    maxPixelCount: Int = SpiralPreset.default.renderOptions.maxPixelCount,
    width: CGFloat? = SpiralPreset.default.renderOptions.width,
    height: CGFloat? = SpiralPreset.default.renderOptions.height,
    image: ShaderImage? = SpiralPreset.default.image
  ) {
    self.init(
      params: SpiralParams(
        colorBack: colorBack,
        colorFront: colorFront,
        density: density,
        distortion: distortion,
        strokeWidth: strokeWidth,
        strokeTaper: strokeTaper,
        strokeCap: strokeCap,
        noise: noise,
        noiseFrequency: noiseFrequency,
        softness: softness
      ),
      sizing: ShaderSizingParams(
        fit: fit, scale: scale, rotation: rotation, originX: originX, originY: originY,
        offsetX: offsetX, offsetY: offsetY, worldWidth: worldWidth, worldHeight: worldHeight),
      motion: ShaderMotionParams(speed: speed, frame: frame),
      renderOptions: ShaderRenderOptions(
        minPixelRatio: minPixelRatio, maxPixelCount: maxPixelCount, width: width, height: height),
      image: image
    )
  }
}

extension Swirl {
  public init(
    colorBack: ShaderColor = SwirlPreset.default.params.colorBack,
    colors: [ShaderColor] = SwirlPreset.default.params.colors,
    bandCount: Float = SwirlPreset.default.params.bandCount,
    twist: Float = SwirlPreset.default.params.twist,
    center: Float = SwirlPreset.default.params.center,
    proportion: Float = SwirlPreset.default.params.proportion,
    softness: Float = SwirlPreset.default.params.softness,
    noise: Float = SwirlPreset.default.params.noise,
    noiseFrequency: Float = SwirlPreset.default.params.noiseFrequency,
    fit: ShaderFit = SwirlPreset.default.sizing.fit,
    scale: Float = SwirlPreset.default.sizing.scale,
    rotation: Float = SwirlPreset.default.sizing.rotation,
    originX: Float = SwirlPreset.default.sizing.originX,
    originY: Float = SwirlPreset.default.sizing.originY,
    offsetX: Float = SwirlPreset.default.sizing.offsetX,
    offsetY: Float = SwirlPreset.default.sizing.offsetY,
    worldWidth: Float = SwirlPreset.default.sizing.worldWidth,
    worldHeight: Float = SwirlPreset.default.sizing.worldHeight,
    speed: Float = SwirlPreset.default.motion.speed,
    frame: Float = SwirlPreset.default.motion.frame,
    minPixelRatio: Float = SwirlPreset.default.renderOptions.minPixelRatio,
    maxPixelCount: Int = SwirlPreset.default.renderOptions.maxPixelCount,
    width: CGFloat? = SwirlPreset.default.renderOptions.width,
    height: CGFloat? = SwirlPreset.default.renderOptions.height,
    image: ShaderImage? = SwirlPreset.default.image
  ) {
    self.init(
      params: SwirlParams(
        colorBack: colorBack,
        colors: colors,
        bandCount: bandCount,
        twist: twist,
        center: center,
        proportion: proportion,
        softness: softness,
        noise: noise,
        noiseFrequency: noiseFrequency
      ),
      sizing: ShaderSizingParams(
        fit: fit, scale: scale, rotation: rotation, originX: originX, originY: originY,
        offsetX: offsetX, offsetY: offsetY, worldWidth: worldWidth, worldHeight: worldHeight),
      motion: ShaderMotionParams(speed: speed, frame: frame),
      renderOptions: ShaderRenderOptions(
        minPixelRatio: minPixelRatio, maxPixelCount: maxPixelCount, width: width, height: height),
      image: image
    )
  }
}

extension Dithering {
  public init(
    colorBack: ShaderColor = DitheringPreset.default.params.colorBack,
    colorFront: ShaderColor = DitheringPreset.default.params.colorFront,
    shape: DitheringShape = DitheringPreset.default.params.shape,
    type: DitheringType = DitheringPreset.default.params.type,
    size: Float = DitheringPreset.default.params.size,
    fit: ShaderFit = DitheringPreset.default.sizing.fit,
    scale: Float = DitheringPreset.default.sizing.scale,
    rotation: Float = DitheringPreset.default.sizing.rotation,
    originX: Float = DitheringPreset.default.sizing.originX,
    originY: Float = DitheringPreset.default.sizing.originY,
    offsetX: Float = DitheringPreset.default.sizing.offsetX,
    offsetY: Float = DitheringPreset.default.sizing.offsetY,
    worldWidth: Float = DitheringPreset.default.sizing.worldWidth,
    worldHeight: Float = DitheringPreset.default.sizing.worldHeight,
    speed: Float = DitheringPreset.default.motion.speed,
    frame: Float = DitheringPreset.default.motion.frame,
    minPixelRatio: Float = DitheringPreset.default.renderOptions.minPixelRatio,
    maxPixelCount: Int = DitheringPreset.default.renderOptions.maxPixelCount,
    width: CGFloat? = DitheringPreset.default.renderOptions.width,
    height: CGFloat? = DitheringPreset.default.renderOptions.height,
    image: ShaderImage? = DitheringPreset.default.image
  ) {
    self.init(
      params: DitheringParams(
        colorBack: colorBack,
        colorFront: colorFront,
        shape: shape,
        type: type,
        size: size
      ),
      sizing: ShaderSizingParams(
        fit: fit, scale: scale, rotation: rotation, originX: originX, originY: originY,
        offsetX: offsetX, offsetY: offsetY, worldWidth: worldWidth, worldHeight: worldHeight),
      motion: ShaderMotionParams(speed: speed, frame: frame),
      renderOptions: ShaderRenderOptions(
        minPixelRatio: minPixelRatio, maxPixelCount: maxPixelCount, width: width, height: height),
      image: image
    )
  }
}

extension GrainGradient {
  public init(
    colorBack: ShaderColor = GrainGradientPreset.default.params.colorBack,
    colors: [ShaderColor] = GrainGradientPreset.default.params.colors,
    softness: Float = GrainGradientPreset.default.params.softness,
    intensity: Float = GrainGradientPreset.default.params.intensity,
    noise: Float = GrainGradientPreset.default.params.noise,
    shape: GrainGradientShape = GrainGradientPreset.default.params.shape,
    fit: ShaderFit = GrainGradientPreset.default.sizing.fit,
    scale: Float = GrainGradientPreset.default.sizing.scale,
    rotation: Float = GrainGradientPreset.default.sizing.rotation,
    originX: Float = GrainGradientPreset.default.sizing.originX,
    originY: Float = GrainGradientPreset.default.sizing.originY,
    offsetX: Float = GrainGradientPreset.default.sizing.offsetX,
    offsetY: Float = GrainGradientPreset.default.sizing.offsetY,
    worldWidth: Float = GrainGradientPreset.default.sizing.worldWidth,
    worldHeight: Float = GrainGradientPreset.default.sizing.worldHeight,
    speed: Float = GrainGradientPreset.default.motion.speed,
    frame: Float = GrainGradientPreset.default.motion.frame,
    minPixelRatio: Float = GrainGradientPreset.default.renderOptions.minPixelRatio,
    maxPixelCount: Int = GrainGradientPreset.default.renderOptions.maxPixelCount,
    width: CGFloat? = GrainGradientPreset.default.renderOptions.width,
    height: CGFloat? = GrainGradientPreset.default.renderOptions.height,
    image: ShaderImage? = GrainGradientPreset.default.image
  ) {
    self.init(
      params: GrainGradientParams(
        colorBack: colorBack,
        colors: colors,
        softness: softness,
        intensity: intensity,
        noise: noise,
        shape: shape
      ),
      sizing: ShaderSizingParams(
        fit: fit, scale: scale, rotation: rotation, originX: originX, originY: originY,
        offsetX: offsetX, offsetY: offsetY, worldWidth: worldWidth, worldHeight: worldHeight),
      motion: ShaderMotionParams(speed: speed, frame: frame),
      renderOptions: ShaderRenderOptions(
        minPixelRatio: minPixelRatio, maxPixelCount: maxPixelCount, width: width, height: height),
      image: image
    )
  }
}

extension PulsingBorder {
  public init(
    colorBack: ShaderColor = PulsingBorderPreset.default.params.colorBack,
    colors: [ShaderColor] = PulsingBorderPreset.default.params.colors,
    roundness: Float = PulsingBorderPreset.default.params.roundness,
    thickness: Float = PulsingBorderPreset.default.params.thickness,
    marginLeft: Float = PulsingBorderPreset.default.params.marginLeft,
    marginRight: Float = PulsingBorderPreset.default.params.marginRight,
    marginTop: Float = PulsingBorderPreset.default.params.marginTop,
    marginBottom: Float = PulsingBorderPreset.default.params.marginBottom,
    aspectRatio: PulsingBorderAspectRatio = PulsingBorderPreset.default.params.aspectRatio,
    softness: Float = PulsingBorderPreset.default.params.softness,
    intensity: Float = PulsingBorderPreset.default.params.intensity,
    bloom: Float = PulsingBorderPreset.default.params.bloom,
    spots: Float = PulsingBorderPreset.default.params.spots,
    spotSize: Float = PulsingBorderPreset.default.params.spotSize,
    pulse: Float = PulsingBorderPreset.default.params.pulse,
    smoke: Float = PulsingBorderPreset.default.params.smoke,
    smokeSize: Float = PulsingBorderPreset.default.params.smokeSize,
    fit: ShaderFit = PulsingBorderPreset.default.sizing.fit,
    scale: Float = PulsingBorderPreset.default.sizing.scale,
    rotation: Float = PulsingBorderPreset.default.sizing.rotation,
    originX: Float = PulsingBorderPreset.default.sizing.originX,
    originY: Float = PulsingBorderPreset.default.sizing.originY,
    offsetX: Float = PulsingBorderPreset.default.sizing.offsetX,
    offsetY: Float = PulsingBorderPreset.default.sizing.offsetY,
    worldWidth: Float = PulsingBorderPreset.default.sizing.worldWidth,
    worldHeight: Float = PulsingBorderPreset.default.sizing.worldHeight,
    speed: Float = PulsingBorderPreset.default.motion.speed,
    frame: Float = PulsingBorderPreset.default.motion.frame,
    minPixelRatio: Float = PulsingBorderPreset.default.renderOptions.minPixelRatio,
    maxPixelCount: Int = PulsingBorderPreset.default.renderOptions.maxPixelCount,
    width: CGFloat? = PulsingBorderPreset.default.renderOptions.width,
    height: CGFloat? = PulsingBorderPreset.default.renderOptions.height,
    image: ShaderImage? = PulsingBorderPreset.default.image
  ) {
    self.init(
      params: PulsingBorderParams(
        colorBack: colorBack,
        colors: colors,
        roundness: roundness,
        thickness: thickness,
        marginLeft: marginLeft,
        marginRight: marginRight,
        marginTop: marginTop,
        marginBottom: marginBottom,
        aspectRatio: aspectRatio,
        softness: softness,
        intensity: intensity,
        bloom: bloom,
        spots: spots,
        spotSize: spotSize,
        pulse: pulse,
        smoke: smoke,
        smokeSize: smokeSize
      ),
      sizing: ShaderSizingParams(
        fit: fit, scale: scale, rotation: rotation, originX: originX, originY: originY,
        offsetX: offsetX, offsetY: offsetY, worldWidth: worldWidth, worldHeight: worldHeight),
      motion: ShaderMotionParams(speed: speed, frame: frame),
      renderOptions: ShaderRenderOptions(
        minPixelRatio: minPixelRatio, maxPixelCount: maxPixelCount, width: width, height: height),
      image: image
    )
  }
}

extension ColorPanels {
  public init(
    colors: [ShaderColor] = ColorPanelsPreset.default.params.colors,
    colorBack: ShaderColor = ColorPanelsPreset.default.params.colorBack,
    density: Float = ColorPanelsPreset.default.params.density,
    angle1: Float = ColorPanelsPreset.default.params.angle1,
    angle2: Float = ColorPanelsPreset.default.params.angle2,
    length: Float = ColorPanelsPreset.default.params.length,
    edges: Float = ColorPanelsPreset.default.params.edges,
    blur: Float = ColorPanelsPreset.default.params.blur,
    fadeIn: Float = ColorPanelsPreset.default.params.fadeIn,
    fadeOut: Float = ColorPanelsPreset.default.params.fadeOut,
    gradient: Float = ColorPanelsPreset.default.params.gradient,
    fit: ShaderFit = ColorPanelsPreset.default.sizing.fit,
    scale: Float = ColorPanelsPreset.default.sizing.scale,
    rotation: Float = ColorPanelsPreset.default.sizing.rotation,
    originX: Float = ColorPanelsPreset.default.sizing.originX,
    originY: Float = ColorPanelsPreset.default.sizing.originY,
    offsetX: Float = ColorPanelsPreset.default.sizing.offsetX,
    offsetY: Float = ColorPanelsPreset.default.sizing.offsetY,
    worldWidth: Float = ColorPanelsPreset.default.sizing.worldWidth,
    worldHeight: Float = ColorPanelsPreset.default.sizing.worldHeight,
    speed: Float = ColorPanelsPreset.default.motion.speed,
    frame: Float = ColorPanelsPreset.default.motion.frame,
    minPixelRatio: Float = ColorPanelsPreset.default.renderOptions.minPixelRatio,
    maxPixelCount: Int = ColorPanelsPreset.default.renderOptions.maxPixelCount,
    width: CGFloat? = ColorPanelsPreset.default.renderOptions.width,
    height: CGFloat? = ColorPanelsPreset.default.renderOptions.height,
    image: ShaderImage? = ColorPanelsPreset.default.image
  ) {
    self.init(
      params: ColorPanelsParams(
        colors: colors,
        colorBack: colorBack,
        density: density,
        angle1: angle1,
        angle2: angle2,
        length: length,
        edges: edges,
        blur: blur,
        fadeIn: fadeIn,
        fadeOut: fadeOut,
        gradient: gradient
      ),
      sizing: ShaderSizingParams(
        fit: fit, scale: scale, rotation: rotation, originX: originX, originY: originY,
        offsetX: offsetX, offsetY: offsetY, worldWidth: worldWidth, worldHeight: worldHeight),
      motion: ShaderMotionParams(speed: speed, frame: frame),
      renderOptions: ShaderRenderOptions(
        minPixelRatio: minPixelRatio, maxPixelCount: maxPixelCount, width: width, height: height),
      image: image
    )
  }
}

extension StaticMeshGradient {
  public init(
    colors: [ShaderColor] = StaticMeshGradientPreset.default.params.colors,
    positions: Float = StaticMeshGradientPreset.default.params.positions,
    waveX: Float = StaticMeshGradientPreset.default.params.waveX,
    waveXShift: Float = StaticMeshGradientPreset.default.params.waveXShift,
    waveY: Float = StaticMeshGradientPreset.default.params.waveY,
    waveYShift: Float = StaticMeshGradientPreset.default.params.waveYShift,
    mixing: Float = StaticMeshGradientPreset.default.params.mixing,
    grainMixer: Float = StaticMeshGradientPreset.default.params.grainMixer,
    grainOverlay: Float = StaticMeshGradientPreset.default.params.grainOverlay,
    fit: ShaderFit = StaticMeshGradientPreset.default.sizing.fit,
    scale: Float = StaticMeshGradientPreset.default.sizing.scale,
    rotation: Float = StaticMeshGradientPreset.default.sizing.rotation,
    originX: Float = StaticMeshGradientPreset.default.sizing.originX,
    originY: Float = StaticMeshGradientPreset.default.sizing.originY,
    offsetX: Float = StaticMeshGradientPreset.default.sizing.offsetX,
    offsetY: Float = StaticMeshGradientPreset.default.sizing.offsetY,
    worldWidth: Float = StaticMeshGradientPreset.default.sizing.worldWidth,
    worldHeight: Float = StaticMeshGradientPreset.default.sizing.worldHeight,
    speed: Float = StaticMeshGradientPreset.default.motion.speed,
    frame: Float = StaticMeshGradientPreset.default.motion.frame,
    minPixelRatio: Float = StaticMeshGradientPreset.default.renderOptions.minPixelRatio,
    maxPixelCount: Int = StaticMeshGradientPreset.default.renderOptions.maxPixelCount,
    width: CGFloat? = StaticMeshGradientPreset.default.renderOptions.width,
    height: CGFloat? = StaticMeshGradientPreset.default.renderOptions.height,
    image: ShaderImage? = StaticMeshGradientPreset.default.image
  ) {
    self.init(
      params: StaticMeshGradientParams(
        colors: colors,
        positions: positions,
        waveX: waveX,
        waveXShift: waveXShift,
        waveY: waveY,
        waveYShift: waveYShift,
        mixing: mixing,
        grainMixer: grainMixer,
        grainOverlay: grainOverlay
      ),
      sizing: ShaderSizingParams(
        fit: fit, scale: scale, rotation: rotation, originX: originX, originY: originY,
        offsetX: offsetX, offsetY: offsetY, worldWidth: worldWidth, worldHeight: worldHeight),
      motion: ShaderMotionParams(speed: speed, frame: frame),
      renderOptions: ShaderRenderOptions(
        minPixelRatio: minPixelRatio, maxPixelCount: maxPixelCount, width: width, height: height),
      image: image
    )
  }
}

extension StaticRadialGradient {
  public init(
    colorBack: ShaderColor = StaticRadialGradientPreset.default.params.colorBack,
    colors: [ShaderColor] = StaticRadialGradientPreset.default.params.colors,
    radius: Float = StaticRadialGradientPreset.default.params.radius,
    focalDistance: Float = StaticRadialGradientPreset.default.params.focalDistance,
    focalAngle: Float = StaticRadialGradientPreset.default.params.focalAngle,
    falloff: Float = StaticRadialGradientPreset.default.params.falloff,
    mixing: Float = StaticRadialGradientPreset.default.params.mixing,
    distortion: Float = StaticRadialGradientPreset.default.params.distortion,
    distortionShift: Float = StaticRadialGradientPreset.default.params.distortionShift,
    distortionFreq: Float = StaticRadialGradientPreset.default.params.distortionFreq,
    grainMixer: Float = StaticRadialGradientPreset.default.params.grainMixer,
    grainOverlay: Float = StaticRadialGradientPreset.default.params.grainOverlay,
    fit: ShaderFit = StaticRadialGradientPreset.default.sizing.fit,
    scale: Float = StaticRadialGradientPreset.default.sizing.scale,
    rotation: Float = StaticRadialGradientPreset.default.sizing.rotation,
    originX: Float = StaticRadialGradientPreset.default.sizing.originX,
    originY: Float = StaticRadialGradientPreset.default.sizing.originY,
    offsetX: Float = StaticRadialGradientPreset.default.sizing.offsetX,
    offsetY: Float = StaticRadialGradientPreset.default.sizing.offsetY,
    worldWidth: Float = StaticRadialGradientPreset.default.sizing.worldWidth,
    worldHeight: Float = StaticRadialGradientPreset.default.sizing.worldHeight,
    speed: Float = StaticRadialGradientPreset.default.motion.speed,
    frame: Float = StaticRadialGradientPreset.default.motion.frame,
    minPixelRatio: Float = StaticRadialGradientPreset.default.renderOptions.minPixelRatio,
    maxPixelCount: Int = StaticRadialGradientPreset.default.renderOptions.maxPixelCount,
    width: CGFloat? = StaticRadialGradientPreset.default.renderOptions.width,
    height: CGFloat? = StaticRadialGradientPreset.default.renderOptions.height,
    image: ShaderImage? = StaticRadialGradientPreset.default.image
  ) {
    self.init(
      params: StaticRadialGradientParams(
        colorBack: colorBack,
        colors: colors,
        radius: radius,
        focalDistance: focalDistance,
        focalAngle: focalAngle,
        falloff: falloff,
        mixing: mixing,
        distortion: distortion,
        distortionShift: distortionShift,
        distortionFreq: distortionFreq,
        grainMixer: grainMixer,
        grainOverlay: grainOverlay
      ),
      sizing: ShaderSizingParams(
        fit: fit, scale: scale, rotation: rotation, originX: originX, originY: originY,
        offsetX: offsetX, offsetY: offsetY, worldWidth: worldWidth, worldHeight: worldHeight),
      motion: ShaderMotionParams(speed: speed, frame: frame),
      renderOptions: ShaderRenderOptions(
        minPixelRatio: minPixelRatio, maxPixelCount: maxPixelCount, width: width, height: height),
      image: image
    )
  }
}

extension PaperTexture {
  public init(
    colorFront: ShaderColor = PaperTexturePreset.default.params.colorFront,
    colorBack: ShaderColor = PaperTexturePreset.default.params.colorBack,
    contrast: Float = PaperTexturePreset.default.params.contrast,
    roughness: Float = PaperTexturePreset.default.params.roughness,
    fiber: Float = PaperTexturePreset.default.params.fiber,
    fiberSize: Float = PaperTexturePreset.default.params.fiberSize,
    crumples: Float = PaperTexturePreset.default.params.crumples,
    foldCount: Float = PaperTexturePreset.default.params.foldCount,
    folds: Float = PaperTexturePreset.default.params.folds,
    fade: Float = PaperTexturePreset.default.params.fade,
    crumpleSize: Float = PaperTexturePreset.default.params.crumpleSize,
    drops: Float = PaperTexturePreset.default.params.drops,
    seed: Float = PaperTexturePreset.default.params.seed,
    fit: ShaderFit = PaperTexturePreset.default.sizing.fit,
    scale: Float = PaperTexturePreset.default.sizing.scale,
    rotation: Float = PaperTexturePreset.default.sizing.rotation,
    originX: Float = PaperTexturePreset.default.sizing.originX,
    originY: Float = PaperTexturePreset.default.sizing.originY,
    offsetX: Float = PaperTexturePreset.default.sizing.offsetX,
    offsetY: Float = PaperTexturePreset.default.sizing.offsetY,
    worldWidth: Float = PaperTexturePreset.default.sizing.worldWidth,
    worldHeight: Float = PaperTexturePreset.default.sizing.worldHeight,
    speed: Float = PaperTexturePreset.default.motion.speed,
    frame: Float = PaperTexturePreset.default.motion.frame,
    minPixelRatio: Float = PaperTexturePreset.default.renderOptions.minPixelRatio,
    maxPixelCount: Int = PaperTexturePreset.default.renderOptions.maxPixelCount,
    width: CGFloat? = PaperTexturePreset.default.renderOptions.width,
    height: CGFloat? = PaperTexturePreset.default.renderOptions.height,
    image: ShaderImage? = PaperTexturePreset.default.image
  ) {
    self.init(
      params: PaperTextureParams(
        colorFront: colorFront,
        colorBack: colorBack,
        contrast: contrast,
        roughness: roughness,
        fiber: fiber,
        fiberSize: fiberSize,
        crumples: crumples,
        foldCount: foldCount,
        folds: folds,
        fade: fade,
        crumpleSize: crumpleSize,
        drops: drops,
        seed: seed
      ),
      sizing: ShaderSizingParams(
        fit: fit, scale: scale, rotation: rotation, originX: originX, originY: originY,
        offsetX: offsetX, offsetY: offsetY, worldWidth: worldWidth, worldHeight: worldHeight),
      motion: ShaderMotionParams(speed: speed, frame: frame),
      renderOptions: ShaderRenderOptions(
        minPixelRatio: minPixelRatio, maxPixelCount: maxPixelCount, width: width, height: height),
      image: image
    )
  }
}

extension FlutedGlass {
  public init(
    colorBack: ShaderColor = FlutedGlassPreset.default.params.colorBack,
    colorShadow: ShaderColor = FlutedGlassPreset.default.params.colorShadow,
    colorHighlight: ShaderColor = FlutedGlassPreset.default.params.colorHighlight,
    shadows: Float = FlutedGlassPreset.default.params.shadows,
    size: Float = FlutedGlassPreset.default.params.size,
    angle: Float = FlutedGlassPreset.default.params.angle,
    distortion: Float = FlutedGlassPreset.default.params.distortion,
    shift: Float = FlutedGlassPreset.default.params.shift,
    blur: Float = FlutedGlassPreset.default.params.blur,
    edges: Float = FlutedGlassPreset.default.params.edges,
    marginLeft: Float = FlutedGlassPreset.default.params.marginLeft,
    marginRight: Float = FlutedGlassPreset.default.params.marginRight,
    marginTop: Float = FlutedGlassPreset.default.params.marginTop,
    marginBottom: Float = FlutedGlassPreset.default.params.marginBottom,
    stretch: Float = FlutedGlassPreset.default.params.stretch,
    distortionShape: GlassDistortionShape = FlutedGlassPreset.default.params.distortionShape,
    highlights: Float = FlutedGlassPreset.default.params.highlights,
    shape: GlassGridShape = FlutedGlassPreset.default.params.shape,
    grainMixer: Float = FlutedGlassPreset.default.params.grainMixer,
    grainOverlay: Float = FlutedGlassPreset.default.params.grainOverlay,
    fit: ShaderFit = FlutedGlassPreset.default.sizing.fit,
    scale: Float = FlutedGlassPreset.default.sizing.scale,
    rotation: Float = FlutedGlassPreset.default.sizing.rotation,
    originX: Float = FlutedGlassPreset.default.sizing.originX,
    originY: Float = FlutedGlassPreset.default.sizing.originY,
    offsetX: Float = FlutedGlassPreset.default.sizing.offsetX,
    offsetY: Float = FlutedGlassPreset.default.sizing.offsetY,
    worldWidth: Float = FlutedGlassPreset.default.sizing.worldWidth,
    worldHeight: Float = FlutedGlassPreset.default.sizing.worldHeight,
    speed: Float = FlutedGlassPreset.default.motion.speed,
    frame: Float = FlutedGlassPreset.default.motion.frame,
    minPixelRatio: Float = FlutedGlassPreset.default.renderOptions.minPixelRatio,
    maxPixelCount: Int = FlutedGlassPreset.default.renderOptions.maxPixelCount,
    width: CGFloat? = FlutedGlassPreset.default.renderOptions.width,
    height: CGFloat? = FlutedGlassPreset.default.renderOptions.height,
    image: ShaderImage? = FlutedGlassPreset.default.image
  ) {
    self.init(
      params: FlutedGlassParams(
        colorBack: colorBack,
        colorShadow: colorShadow,
        colorHighlight: colorHighlight,
        shadows: shadows,
        size: size,
        angle: angle,
        distortion: distortion,
        shift: shift,
        blur: blur,
        edges: edges,
        marginLeft: marginLeft,
        marginRight: marginRight,
        marginTop: marginTop,
        marginBottom: marginBottom,
        stretch: stretch,
        distortionShape: distortionShape,
        highlights: highlights,
        shape: shape,
        grainMixer: grainMixer,
        grainOverlay: grainOverlay
      ),
      sizing: ShaderSizingParams(
        fit: fit, scale: scale, rotation: rotation, originX: originX, originY: originY,
        offsetX: offsetX, offsetY: offsetY, worldWidth: worldWidth, worldHeight: worldHeight),
      motion: ShaderMotionParams(speed: speed, frame: frame),
      renderOptions: ShaderRenderOptions(
        minPixelRatio: minPixelRatio, maxPixelCount: maxPixelCount, width: width, height: height),
      image: image
    )
  }
}

extension Water {
  public init(
    colorBack: ShaderColor = WaterPreset.default.params.colorBack,
    colorHighlight: ShaderColor = WaterPreset.default.params.colorHighlight,
    highlights: Float = WaterPreset.default.params.highlights,
    layering: Float = WaterPreset.default.params.layering,
    edges: Float = WaterPreset.default.params.edges,
    caustic: Float = WaterPreset.default.params.caustic,
    waves: Float = WaterPreset.default.params.waves,
    size: Float = WaterPreset.default.params.size,
    fit: ShaderFit = WaterPreset.default.sizing.fit,
    scale: Float = WaterPreset.default.sizing.scale,
    rotation: Float = WaterPreset.default.sizing.rotation,
    originX: Float = WaterPreset.default.sizing.originX,
    originY: Float = WaterPreset.default.sizing.originY,
    offsetX: Float = WaterPreset.default.sizing.offsetX,
    offsetY: Float = WaterPreset.default.sizing.offsetY,
    worldWidth: Float = WaterPreset.default.sizing.worldWidth,
    worldHeight: Float = WaterPreset.default.sizing.worldHeight,
    speed: Float = WaterPreset.default.motion.speed,
    frame: Float = WaterPreset.default.motion.frame,
    minPixelRatio: Float = WaterPreset.default.renderOptions.minPixelRatio,
    maxPixelCount: Int = WaterPreset.default.renderOptions.maxPixelCount,
    width: CGFloat? = WaterPreset.default.renderOptions.width,
    height: CGFloat? = WaterPreset.default.renderOptions.height,
    image: ShaderImage? = WaterPreset.default.image
  ) {
    self.init(
      params: WaterParams(
        colorBack: colorBack,
        colorHighlight: colorHighlight,
        highlights: highlights,
        layering: layering,
        edges: edges,
        caustic: caustic,
        waves: waves,
        size: size
      ),
      sizing: ShaderSizingParams(
        fit: fit, scale: scale, rotation: rotation, originX: originX, originY: originY,
        offsetX: offsetX, offsetY: offsetY, worldWidth: worldWidth, worldHeight: worldHeight),
      motion: ShaderMotionParams(speed: speed, frame: frame),
      renderOptions: ShaderRenderOptions(
        minPixelRatio: minPixelRatio, maxPixelCount: maxPixelCount, width: width, height: height),
      image: image
    )
  }
}

extension ImageDithering {
  public init(
    colorFront: ShaderColor = ImageDitheringPreset.default.params.colorFront,
    colorBack: ShaderColor = ImageDitheringPreset.default.params.colorBack,
    colorHighlight: ShaderColor = ImageDitheringPreset.default.params.colorHighlight,
    type: DitheringType = ImageDitheringPreset.default.params.type,
    size: Float = ImageDitheringPreset.default.params.size,
    colorSteps: Float = ImageDitheringPreset.default.params.colorSteps,
    originalColors: Float = ImageDitheringPreset.default.params.originalColors,
    inverted: Float = ImageDitheringPreset.default.params.inverted,
    fit: ShaderFit = ImageDitheringPreset.default.sizing.fit,
    scale: Float = ImageDitheringPreset.default.sizing.scale,
    rotation: Float = ImageDitheringPreset.default.sizing.rotation,
    originX: Float = ImageDitheringPreset.default.sizing.originX,
    originY: Float = ImageDitheringPreset.default.sizing.originY,
    offsetX: Float = ImageDitheringPreset.default.sizing.offsetX,
    offsetY: Float = ImageDitheringPreset.default.sizing.offsetY,
    worldWidth: Float = ImageDitheringPreset.default.sizing.worldWidth,
    worldHeight: Float = ImageDitheringPreset.default.sizing.worldHeight,
    speed: Float = ImageDitheringPreset.default.motion.speed,
    frame: Float = ImageDitheringPreset.default.motion.frame,
    minPixelRatio: Float = ImageDitheringPreset.default.renderOptions.minPixelRatio,
    maxPixelCount: Int = ImageDitheringPreset.default.renderOptions.maxPixelCount,
    width: CGFloat? = ImageDitheringPreset.default.renderOptions.width,
    height: CGFloat? = ImageDitheringPreset.default.renderOptions.height,
    image: ShaderImage? = ImageDitheringPreset.default.image
  ) {
    self.init(
      params: ImageDitheringParams(
        colorFront: colorFront,
        colorBack: colorBack,
        colorHighlight: colorHighlight,
        type: type,
        size: size,
        colorSteps: colorSteps,
        originalColors: originalColors,
        inverted: inverted
      ),
      sizing: ShaderSizingParams(
        fit: fit, scale: scale, rotation: rotation, originX: originX, originY: originY,
        offsetX: offsetX, offsetY: offsetY, worldWidth: worldWidth, worldHeight: worldHeight),
      motion: ShaderMotionParams(speed: speed, frame: frame),
      renderOptions: ShaderRenderOptions(
        minPixelRatio: minPixelRatio, maxPixelCount: maxPixelCount, width: width, height: height),
      image: image
    )
  }
}

extension Heatmap {
  public init(
    colorBack: ShaderColor = HeatmapPreset.default.params.colorBack,
    colors: [ShaderColor] = HeatmapPreset.default.params.colors,
    contour: Float = HeatmapPreset.default.params.contour,
    angle: Float = HeatmapPreset.default.params.angle,
    noise: Float = HeatmapPreset.default.params.noise,
    innerGlow: Float = HeatmapPreset.default.params.innerGlow,
    outerGlow: Float = HeatmapPreset.default.params.outerGlow,
    fit: ShaderFit = HeatmapPreset.default.sizing.fit,
    scale: Float = HeatmapPreset.default.sizing.scale,
    rotation: Float = HeatmapPreset.default.sizing.rotation,
    originX: Float = HeatmapPreset.default.sizing.originX,
    originY: Float = HeatmapPreset.default.sizing.originY,
    offsetX: Float = HeatmapPreset.default.sizing.offsetX,
    offsetY: Float = HeatmapPreset.default.sizing.offsetY,
    worldWidth: Float = HeatmapPreset.default.sizing.worldWidth,
    worldHeight: Float = HeatmapPreset.default.sizing.worldHeight,
    speed: Float = HeatmapPreset.default.motion.speed,
    frame: Float = HeatmapPreset.default.motion.frame,
    minPixelRatio: Float = HeatmapPreset.default.renderOptions.minPixelRatio,
    maxPixelCount: Int = HeatmapPreset.default.renderOptions.maxPixelCount,
    width: CGFloat? = HeatmapPreset.default.renderOptions.width,
    height: CGFloat? = HeatmapPreset.default.renderOptions.height,
    image: ShaderImage? = HeatmapPreset.default.image
  ) {
    self.init(
      params: HeatmapParams(
        colorBack: colorBack,
        colors: colors,
        contour: contour,
        angle: angle,
        noise: noise,
        innerGlow: innerGlow,
        outerGlow: outerGlow
      ),
      sizing: ShaderSizingParams(
        fit: fit, scale: scale, rotation: rotation, originX: originX, originY: originY,
        offsetX: offsetX, offsetY: offsetY, worldWidth: worldWidth, worldHeight: worldHeight),
      motion: ShaderMotionParams(speed: speed, frame: frame),
      renderOptions: ShaderRenderOptions(
        minPixelRatio: minPixelRatio, maxPixelCount: maxPixelCount, width: width, height: height),
      image: image
    )
  }
}

extension LiquidMetal {
  public init(
    colorBack: ShaderColor = LiquidMetalPreset.default.params.colorBack,
    colorTint: ShaderColor = LiquidMetalPreset.default.params.colorTint,
    repetition: Float = LiquidMetalPreset.default.params.repetition,
    softness: Float = LiquidMetalPreset.default.params.softness,
    shiftRed: Float = LiquidMetalPreset.default.params.shiftRed,
    shiftBlue: Float = LiquidMetalPreset.default.params.shiftBlue,
    distortion: Float = LiquidMetalPreset.default.params.distortion,
    contour: Float = LiquidMetalPreset.default.params.contour,
    angle: Float = LiquidMetalPreset.default.params.angle,
    shape: LiquidMetalShape = LiquidMetalPreset.default.params.shape,
    fit: ShaderFit = LiquidMetalPreset.default.sizing.fit,
    scale: Float = LiquidMetalPreset.default.sizing.scale,
    rotation: Float = LiquidMetalPreset.default.sizing.rotation,
    originX: Float = LiquidMetalPreset.default.sizing.originX,
    originY: Float = LiquidMetalPreset.default.sizing.originY,
    offsetX: Float = LiquidMetalPreset.default.sizing.offsetX,
    offsetY: Float = LiquidMetalPreset.default.sizing.offsetY,
    worldWidth: Float = LiquidMetalPreset.default.sizing.worldWidth,
    worldHeight: Float = LiquidMetalPreset.default.sizing.worldHeight,
    speed: Float = LiquidMetalPreset.default.motion.speed,
    frame: Float = LiquidMetalPreset.default.motion.frame,
    minPixelRatio: Float = LiquidMetalPreset.default.renderOptions.minPixelRatio,
    maxPixelCount: Int = LiquidMetalPreset.default.renderOptions.maxPixelCount,
    width: CGFloat? = LiquidMetalPreset.default.renderOptions.width,
    height: CGFloat? = LiquidMetalPreset.default.renderOptions.height,
    image: ShaderImage? = LiquidMetalPreset.default.image
  ) {
    self.init(
      params: LiquidMetalParams(
        colorBack: colorBack,
        colorTint: colorTint,
        repetition: repetition,
        softness: softness,
        shiftRed: shiftRed,
        shiftBlue: shiftBlue,
        distortion: distortion,
        contour: contour,
        angle: angle,
        shape: shape
      ),
      sizing: ShaderSizingParams(
        fit: fit, scale: scale, rotation: rotation, originX: originX, originY: originY,
        offsetX: offsetX, offsetY: offsetY, worldWidth: worldWidth, worldHeight: worldHeight),
      motion: ShaderMotionParams(speed: speed, frame: frame),
      renderOptions: ShaderRenderOptions(
        minPixelRatio: minPixelRatio, maxPixelCount: maxPixelCount, width: width, height: height),
      image: image
    )
  }
}

extension HalftoneDots {
  public init(
    colorFront: ShaderColor = HalftoneDotsPreset.default.params.colorFront,
    colorBack: ShaderColor = HalftoneDotsPreset.default.params.colorBack,
    size: Float = HalftoneDotsPreset.default.params.size,
    grid: HalftoneDotsGrid = HalftoneDotsPreset.default.params.grid,
    radius: Float = HalftoneDotsPreset.default.params.radius,
    contrast: Float = HalftoneDotsPreset.default.params.contrast,
    originalColors: Float = HalftoneDotsPreset.default.params.originalColors,
    inverted: Float = HalftoneDotsPreset.default.params.inverted,
    grainMixer: Float = HalftoneDotsPreset.default.params.grainMixer,
    grainOverlay: Float = HalftoneDotsPreset.default.params.grainOverlay,
    grainSize: Float = HalftoneDotsPreset.default.params.grainSize,
    type: HalftoneDotsType = HalftoneDotsPreset.default.params.type,
    fit: ShaderFit = HalftoneDotsPreset.default.sizing.fit,
    scale: Float = HalftoneDotsPreset.default.sizing.scale,
    rotation: Float = HalftoneDotsPreset.default.sizing.rotation,
    originX: Float = HalftoneDotsPreset.default.sizing.originX,
    originY: Float = HalftoneDotsPreset.default.sizing.originY,
    offsetX: Float = HalftoneDotsPreset.default.sizing.offsetX,
    offsetY: Float = HalftoneDotsPreset.default.sizing.offsetY,
    worldWidth: Float = HalftoneDotsPreset.default.sizing.worldWidth,
    worldHeight: Float = HalftoneDotsPreset.default.sizing.worldHeight,
    speed: Float = HalftoneDotsPreset.default.motion.speed,
    frame: Float = HalftoneDotsPreset.default.motion.frame,
    minPixelRatio: Float = HalftoneDotsPreset.default.renderOptions.minPixelRatio,
    maxPixelCount: Int = HalftoneDotsPreset.default.renderOptions.maxPixelCount,
    width: CGFloat? = HalftoneDotsPreset.default.renderOptions.width,
    height: CGFloat? = HalftoneDotsPreset.default.renderOptions.height,
    image: ShaderImage? = HalftoneDotsPreset.default.image
  ) {
    self.init(
      params: HalftoneDotsParams(
        colorFront: colorFront,
        colorBack: colorBack,
        size: size,
        grid: grid,
        radius: radius,
        contrast: contrast,
        originalColors: originalColors,
        inverted: inverted,
        grainMixer: grainMixer,
        grainOverlay: grainOverlay,
        grainSize: grainSize,
        type: type
      ),
      sizing: ShaderSizingParams(
        fit: fit, scale: scale, rotation: rotation, originX: originX, originY: originY,
        offsetX: offsetX, offsetY: offsetY, worldWidth: worldWidth, worldHeight: worldHeight),
      motion: ShaderMotionParams(speed: speed, frame: frame),
      renderOptions: ShaderRenderOptions(
        minPixelRatio: minPixelRatio, maxPixelCount: maxPixelCount, width: width, height: height),
      image: image
    )
  }
}

extension HalftoneCmyk {
  public init(
    colorBack: ShaderColor = HalftoneCmykPreset.default.params.colorBack,
    colorC: ShaderColor = HalftoneCmykPreset.default.params.colorC,
    colorM: ShaderColor = HalftoneCmykPreset.default.params.colorM,
    colorY: ShaderColor = HalftoneCmykPreset.default.params.colorY,
    colorK: ShaderColor = HalftoneCmykPreset.default.params.colorK,
    size: Float = HalftoneCmykPreset.default.params.size,
    contrast: Float = HalftoneCmykPreset.default.params.contrast,
    softness: Float = HalftoneCmykPreset.default.params.softness,
    grainSize: Float = HalftoneCmykPreset.default.params.grainSize,
    grainMixer: Float = HalftoneCmykPreset.default.params.grainMixer,
    grainOverlay: Float = HalftoneCmykPreset.default.params.grainOverlay,
    gridNoise: Float = HalftoneCmykPreset.default.params.gridNoise,
    floodC: Float = HalftoneCmykPreset.default.params.floodC,
    floodM: Float = HalftoneCmykPreset.default.params.floodM,
    floodY: Float = HalftoneCmykPreset.default.params.floodY,
    floodK: Float = HalftoneCmykPreset.default.params.floodK,
    gainC: Float = HalftoneCmykPreset.default.params.gainC,
    gainM: Float = HalftoneCmykPreset.default.params.gainM,
    gainY: Float = HalftoneCmykPreset.default.params.gainY,
    gainK: Float = HalftoneCmykPreset.default.params.gainK,
    type: HalftoneCmykType = HalftoneCmykPreset.default.params.type,
    fit: ShaderFit = HalftoneCmykPreset.default.sizing.fit,
    scale: Float = HalftoneCmykPreset.default.sizing.scale,
    rotation: Float = HalftoneCmykPreset.default.sizing.rotation,
    originX: Float = HalftoneCmykPreset.default.sizing.originX,
    originY: Float = HalftoneCmykPreset.default.sizing.originY,
    offsetX: Float = HalftoneCmykPreset.default.sizing.offsetX,
    offsetY: Float = HalftoneCmykPreset.default.sizing.offsetY,
    worldWidth: Float = HalftoneCmykPreset.default.sizing.worldWidth,
    worldHeight: Float = HalftoneCmykPreset.default.sizing.worldHeight,
    speed: Float = HalftoneCmykPreset.default.motion.speed,
    frame: Float = HalftoneCmykPreset.default.motion.frame,
    minPixelRatio: Float = HalftoneCmykPreset.default.renderOptions.minPixelRatio,
    maxPixelCount: Int = HalftoneCmykPreset.default.renderOptions.maxPixelCount,
    width: CGFloat? = HalftoneCmykPreset.default.renderOptions.width,
    height: CGFloat? = HalftoneCmykPreset.default.renderOptions.height,
    image: ShaderImage? = HalftoneCmykPreset.default.image
  ) {
    self.init(
      params: HalftoneCmykParams(
        colorBack: colorBack,
        colorC: colorC,
        colorM: colorM,
        colorY: colorY,
        colorK: colorK,
        size: size,
        contrast: contrast,
        softness: softness,
        grainSize: grainSize,
        grainMixer: grainMixer,
        grainOverlay: grainOverlay,
        gridNoise: gridNoise,
        floodC: floodC,
        floodM: floodM,
        floodY: floodY,
        floodK: floodK,
        gainC: gainC,
        gainM: gainM,
        gainY: gainY,
        gainK: gainK,
        type: type
      ),
      sizing: ShaderSizingParams(
        fit: fit, scale: scale, rotation: rotation, originX: originX, originY: originY,
        offsetX: offsetX, offsetY: offsetY, worldWidth: worldWidth, worldHeight: worldHeight),
      motion: ShaderMotionParams(speed: speed, frame: frame),
      renderOptions: ShaderRenderOptions(
        minPixelRatio: minPixelRatio, maxPixelCount: maxPixelCount, width: width, height: height),
      image: image
    )
  }
}

extension GemSmoke {
  public init(
    colors: [ShaderColor] = GemSmokePreset.default.params.colors,
    colorBack: ShaderColor = GemSmokePreset.default.params.colorBack,
    colorInner: ShaderColor = GemSmokePreset.default.params.colorInner,
    innerDistortion: Float = GemSmokePreset.default.params.innerDistortion,
    outerDistortion: Float = GemSmokePreset.default.params.outerDistortion,
    outerGlow: Float = GemSmokePreset.default.params.outerGlow,
    innerGlow: Float = GemSmokePreset.default.params.innerGlow,
    offset: Float = GemSmokePreset.default.params.offset,
    angle: Float = GemSmokePreset.default.params.angle,
    size: Float = GemSmokePreset.default.params.size,
    shape: GemSmokeShape = GemSmokePreset.default.params.shape,
    fit: ShaderFit = GemSmokePreset.default.sizing.fit,
    scale: Float = GemSmokePreset.default.sizing.scale,
    rotation: Float = GemSmokePreset.default.sizing.rotation,
    originX: Float = GemSmokePreset.default.sizing.originX,
    originY: Float = GemSmokePreset.default.sizing.originY,
    offsetX: Float = GemSmokePreset.default.sizing.offsetX,
    offsetY: Float = GemSmokePreset.default.sizing.offsetY,
    worldWidth: Float = GemSmokePreset.default.sizing.worldWidth,
    worldHeight: Float = GemSmokePreset.default.sizing.worldHeight,
    speed: Float = GemSmokePreset.default.motion.speed,
    frame: Float = GemSmokePreset.default.motion.frame,
    minPixelRatio: Float = GemSmokePreset.default.renderOptions.minPixelRatio,
    maxPixelCount: Int = GemSmokePreset.default.renderOptions.maxPixelCount,
    width: CGFloat? = GemSmokePreset.default.renderOptions.width,
    height: CGFloat? = GemSmokePreset.default.renderOptions.height,
    image: ShaderImage? = GemSmokePreset.default.image
  ) {
    self.init(
      params: GemSmokeParams(
        colors: colors,
        colorBack: colorBack,
        colorInner: colorInner,
        innerDistortion: innerDistortion,
        outerDistortion: outerDistortion,
        outerGlow: outerGlow,
        innerGlow: innerGlow,
        offset: offset,
        angle: angle,
        size: size,
        shape: shape
      ),
      sizing: ShaderSizingParams(
        fit: fit, scale: scale, rotation: rotation, originX: originX, originY: originY,
        offsetX: offsetX, offsetY: offsetY, worldWidth: worldWidth, worldHeight: worldHeight),
      motion: ShaderMotionParams(speed: speed, frame: frame),
      renderOptions: ShaderRenderOptions(
        minPixelRatio: minPixelRatio, maxPixelCount: maxPixelCount, width: width, height: height),
      image: image
    )
  }
}
