// Shared shader table consumed by both generate-swift-presets.mjs (Swift codegen)
// and parity-harness/generate-goldens.mjs (golden image generation), so both
// sides always iterate the identical shader × preset matrix.
//
// Per-spec fields:
//   key           kebab-case shader key (matches paper repo file/preset namespace)
//   componentName PascalCase name — the @paper-design/shaders-react export used
//                 by the parity harness
//   viewName      optional override for the SwiftUI view struct name when it
//                 differs from the Paper export. Defaults to componentName.
//   arrayName     preset array name in the Paper snapshot
//   swiftArrayName optional generated preset array name in Presets.swift.
//                 Defaults to arrayName.
//   presetType / paramsType   Swift type names for codegen
//   fields        param fields in Swift declaration order; string when Swift and
//                 paper names match, else { swift, paper?, enum?, defaultValue? }
//   isStatic      true when the fragment shader has no u_time uniform — goldens
//                 only need frame 0
//   usesImage     true when parity cases supply the shared fixture image (shaders
//                 whose u_image drives the output). liquid-metal and gem-smoke
//                 take an image but are tested in shape mode (no image) because
//                 their presets don't set one.

export const sizingKeys = [
  "fit",
  "scale",
  "rotation",
  "originX",
  "originY",
  "offsetX",
  "offsetY",
  "worldWidth",
  "worldHeight",
];

export const defaultSizing = {
  fit: "contain",
  scale: 1,
  rotation: 0,
  originX: 0.5,
  originY: 0.5,
  offsetX: 0,
  offsetY: 0,
  worldWidth: 0,
  worldHeight: 0,
};

// Golden image geometry (also recorded in the manifest).
export const goldenCanvas = { width: 320, height: 240, pixelRatio: 1 };

// u_time in milliseconds; static shaders render frame 0 only.
export const animatedFrames = [0, 5000];
export const staticFrames = [0];

export function framesFor(spec) {
  if (spec.frames) return spec.frames;
  return spec.isStatic ? staticFrames : animatedFrames;
}

export const specs = [
  {
    key: "mesh-gradient",
    componentName: "MeshGradient",
    viewName: "AnimatedMeshGradient",
    arrayName: "meshGradientPresets",
    swiftArrayName: "animatedMeshGradientPresets",
    presetType: "AnimatedMeshGradientPreset",
    paramsType: "AnimatedMeshGradientParams",
    fields: ["colors", "distortion", "swirl", "grainMixer", "grainOverlay"],
  },
  {
    key: "smoke-ring",
    componentName: "SmokeRing",
    arrayName: "smokeRingPresets",
    presetType: "SmokeRingPreset",
    paramsType: "SmokeRingParams",
    fields: ["colorBack", "colors", "noiseScale", "thickness", "radius", "innerShape", "noiseIterations"],
  },
  {
    key: "neuro-noise",
    componentName: "NeuroNoise",
    arrayName: "neuroNoisePresets",
    presetType: "NeuroNoisePreset",
    paramsType: "NeuroNoiseParams",
    fields: ["colorFront", "colorMid", "colorBack", "brightness", "contrast"],
  },
  {
    key: "dot-orbit",
    componentName: "DotOrbit",
    arrayName: "dotOrbitPresets",
    presetType: "DotOrbitPreset",
    paramsType: "DotOrbitParams",
    fields: ["colorBack", "colors", "stepsPerColor", "size", "sizeRange", "spreading"],
  },
  {
    key: "dot-grid",
    componentName: "DotGrid",
    arrayName: "dotGridPresets",
    presetType: "DotGridPreset",
    paramsType: "DotGridParams",
    renderOptions: "ShaderRenderOptions(maxPixelCount: 6016 * 3384)",
    isStatic: true,
    fields: [
      "colorBack",
      "colorFill",
      "colorStroke",
      { swift: "dotSize", paper: "size" },
      "gapX",
      "gapY",
      "strokeWidth",
      "sizeRange",
      "opacityRange",
      { swift: "shape", enum: "DotGridShapes" },
    ],
  },
  {
    key: "simplex-noise",
    componentName: "SimplexNoise",
    arrayName: "simplexNoisePresets",
    presetType: "SimplexNoisePreset",
    paramsType: "SimplexNoiseParams",
    fields: ["colors", "stepsPerColor", "softness"],
  },
  {
    key: "metaballs",
    componentName: "Metaballs",
    arrayName: "metaballsPresets",
    presetType: "MetaballsPreset",
    paramsType: "MetaballsParams",
    fields: ["colorBack", "colors", "count", "size", { swift: "sizeRange", defaultValue: 0.2 }],
  },
  {
    key: "waves",
    componentName: "Waves",
    arrayName: "wavesPresets",
    presetType: "WavesPreset",
    paramsType: "WavesParams",
    renderOptions: "ShaderRenderOptions(maxPixelCount: 6016 * 3384)",
    isStatic: true,
    fields: ["colorFront", "colorBack", "shape", "frequency", "amplitude", "spacing", "proportion", "softness"],
  },
  {
    key: "perlin-noise",
    componentName: "PerlinNoise",
    arrayName: "perlinNoisePresets",
    presetType: "PerlinNoisePreset",
    paramsType: "PerlinNoiseParams",
    fields: ["colorFront", "colorBack", "proportion", "softness", "octaveCount", "persistence", "lacunarity"],
  },
  {
    key: "voronoi",
    componentName: "Voronoi",
    arrayName: "voronoiPresets",
    presetType: "VoronoiPreset",
    paramsType: "VoronoiParams",
    fields: ["colors", "stepsPerColor", "colorGap", "colorGlow", "distortion", "gap", "glow"],
  },
  {
    key: "warp",
    componentName: "Warp",
    arrayName: "warpPresets",
    presetType: "WarpPreset",
    paramsType: "WarpParams",
    fields: [
      "colors",
      "proportion",
      "softness",
      { swift: "shape", enum: "WarpPatterns" },
      "shapeScale",
      "distortion",
      "swirl",
      "swirlIterations",
    ],
  },
  {
    key: "god-rays",
    componentName: "GodRays",
    arrayName: "godRaysPresets",
    presetType: "GodRaysPreset",
    paramsType: "GodRaysParams",
    fields: [
      "colorBack",
      "colorBloom",
      "colors",
      "density",
      "spotty",
      "midSize",
      "midIntensity",
      "intensity",
      "bloom",
    ],
  },
  {
    key: "spiral",
    componentName: "Spiral",
    arrayName: "spiralPresets",
    presetType: "SpiralPreset",
    paramsType: "SpiralParams",
    fields: [
      "colorBack",
      "colorFront",
      "density",
      "distortion",
      "strokeWidth",
      "strokeTaper",
      "strokeCap",
      "noise",
      "noiseFrequency",
      "softness",
    ],
  },
  {
    key: "swirl",
    componentName: "Swirl",
    arrayName: "swirlPresets",
    presetType: "SwirlPreset",
    paramsType: "SwirlParams",
    fields: ["colorBack", "colors", "bandCount", "twist", "center", "proportion", "softness", "noise", "noiseFrequency"],
  },
  {
    key: "dithering",
    componentName: "Dithering",
    arrayName: "ditheringPresets",
    presetType: "DitheringPreset",
    paramsType: "DitheringParams",
    fields: ["colorBack", "colorFront", { swift: "shape", enum: "DitheringShapes" }, { swift: "type", enum: "DitheringTypes" }, "size"],
  },
  {
    key: "grain-gradient",
    componentName: "GrainGradient",
    arrayName: "grainGradientPresets",
    presetType: "GrainGradientPreset",
    paramsType: "GrainGradientParams",
    fields: ["colorBack", "colors", "softness", "intensity", "noise", { swift: "shape", enum: "GrainGradientShapes" }],
  },
  {
    key: "pulsing-border",
    componentName: "PulsingBorder",
    arrayName: "pulsingBorderPresets",
    presetType: "PulsingBorderPreset",
    paramsType: "PulsingBorderParams",
    fields: [
      "colorBack",
      "colors",
      "roundness",
      "thickness",
      "marginLeft",
      "marginRight",
      "marginTop",
      "marginBottom",
      { swift: "aspectRatio", enum: "PulsingBorderAspectRatios" },
      "softness",
      "intensity",
      "bloom",
      "spots",
      "spotSize",
      "pulse",
      "smoke",
      "smokeSize",
    ],
  },
  {
    key: "color-panels",
    componentName: "ColorPanels",
    arrayName: "colorPanelsPresets",
    presetType: "ColorPanelsPreset",
    paramsType: "ColorPanelsParams",
    fields: ["colors", "colorBack", "density", "angle1", "angle2", "length", "edges", "blur", "fadeIn", "fadeOut", "gradient"],
  },
  {
    key: "static-mesh-gradient",
    componentName: "StaticMeshGradient",
    arrayName: "staticMeshGradientPresets",
    presetType: "StaticMeshGradientPreset",
    paramsType: "StaticMeshGradientParams",
    isStatic: true,
    fields: ["colors", "positions", "waveX", "waveXShift", "waveY", "waveYShift", "mixing", "grainMixer", "grainOverlay"],
  },
  {
    key: "static-radial-gradient",
    componentName: "StaticRadialGradient",
    arrayName: "staticRadialGradientPresets",
    presetType: "StaticRadialGradientPreset",
    paramsType: "StaticRadialGradientParams",
    isStatic: true,
    fields: [
      "colorBack",
      "colors",
      "radius",
      "focalDistance",
      "focalAngle",
      "falloff",
      "mixing",
      "distortion",
      "distortionShift",
      "distortionFreq",
      "grainMixer",
      "grainOverlay",
    ],
  },
  {
    key: "paper-texture",
    componentName: "PaperTexture",
    arrayName: "paperTexturePresets",
    presetType: "PaperTexturePreset",
    paramsType: "PaperTextureParams",
    isStatic: true,
    usesImage: true,
    fields: [
      "colorFront",
      "colorBack",
      "contrast",
      "roughness",
      "fiber",
      "fiberSize",
      "crumples",
      "foldCount",
      "folds",
      "fade",
      "crumpleSize",
      "drops",
      "seed",
    ],
  },
  {
    key: "fluted-glass",
    componentName: "FlutedGlass",
    arrayName: "flutedGlassPresets",
    presetType: "FlutedGlassPreset",
    paramsType: "FlutedGlassParams",
    isStatic: true,
    usesImage: true,
    fields: [
      "colorBack",
      "colorShadow",
      "colorHighlight",
      "shadows",
      "size",
      "angle",
      "distortion",
      "shift",
      "blur",
      "edges",
      "marginLeft",
      "marginRight",
      "marginTop",
      "marginBottom",
      "stretch",
      { swift: "distortionShape", enum: "GlassDistortionShapes" },
      "highlights",
      { swift: "shape", enum: "GlassGridShapes" },
      "grainMixer",
      "grainOverlay",
    ],
  },
  {
    key: "water",
    componentName: "Water",
    arrayName: "waterPresets",
    presetType: "WaterPreset",
    paramsType: "WaterParams",
    usesImage: true,
    fields: ["colorBack", "colorHighlight", "highlights", "layering", "edges", "caustic", "waves", "size"],
  },
  {
    key: "image-dithering",
    componentName: "ImageDithering",
    arrayName: "imageDitheringPresets",
    presetType: "ImageDitheringPreset",
    paramsType: "ImageDitheringParams",
    isStatic: true,
    usesImage: true,
    fields: [
      "colorFront",
      "colorBack",
      "colorHighlight",
      { swift: "type", enum: "DitheringTypes" },
      "size",
      "colorSteps",
      "originalColors",
      "inverted",
    ],
  },
  {
    key: "heatmap",
    componentName: "Heatmap",
    arrayName: "heatmapPresets",
    presetType: "HeatmapPreset",
    paramsType: "HeatmapParams",
    usesImage: true,
    fields: ["colorBack", "colors", "contour", "angle", "noise", "innerGlow", "outerGlow"],
  },
  {
    key: "liquid-metal",
    componentName: "LiquidMetal",
    arrayName: "liquidMetalPresets",
    presetType: "LiquidMetalPreset",
    paramsType: "LiquidMetalParams",
    fields: [
      "colorBack",
      "colorTint",
      "repetition",
      "softness",
      "shiftRed",
      "shiftBlue",
      "distortion",
      "contour",
      "angle",
      { swift: "shape", enum: "LiquidMetalShapes" },
    ],
  },
  {
    key: "halftone-dots",
    componentName: "HalftoneDots",
    arrayName: "halftoneDotsPresets",
    presetType: "HalftoneDotsPreset",
    paramsType: "HalftoneDotsParams",
    usesImage: true,
    fields: [
      "colorFront",
      "colorBack",
      "size",
      { swift: "grid", enum: "HalftoneDotsGrids" },
      "radius",
      "contrast",
      "originalColors",
      "inverted",
      "grainMixer",
      "grainOverlay",
      "grainSize",
      { swift: "type", enum: "HalftoneDotsTypes" },
    ],
  },
  {
    key: "halftone-cmyk",
    componentName: "HalftoneCmyk",
    viewName: "HalftoneCMYK",
    arrayName: "halftoneCmykPresets",
    swiftArrayName: "halftoneCMYKPresets",
    presetType: "HalftoneCMYKPreset",
    paramsType: "HalftoneCMYKParams",
    isStatic: true,
    usesImage: true,
    fields: [
      "colorBack",
      "colorC",
      "colorM",
      "colorY",
      "colorK",
      "size",
      "contrast",
      "softness",
      "grainSize",
      "grainMixer",
      "grainOverlay",
      "gridNoise",
      "floodC",
      "floodM",
      "floodY",
      "floodK",
      "gainC",
      "gainM",
      "gainY",
      "gainK",
      { swift: "type", enum: "HalftoneCmykTypes" },
    ],
  },
  {
    key: "gem-smoke",
    componentName: "GemSmoke",
    arrayName: "gemSmokePresets",
    presetType: "GemSmokePreset",
    paramsType: "GemSmokeParams",
    fields: [
      "colors",
      "colorBack",
      "colorInner",
      "innerDistortion",
      "outerDistortion",
      "outerGlow",
      "innerGlow",
      "offset",
      "angle",
      "size",
      { swift: "shape", enum: "GemSmokeShapes" },
    ],
  },
];
